### ISSUE TITLE
Strange behavior on iOS when running the sample

### ISSUE THREAD

**Issue by gviddy** [jamesmontemagno/ConnectivityPlugin#1]
Please fill out either the bug or feature request section and remove whatever section you are not using.
## Bug

Version Number of Plugin: 2.2.2 (download of code from today)
Device Tested On: iPhone 4
Simulator Tested On: iPhone 6s
### Expected Behavior

Run the sample, click connectivity test and all default hosts should be 'Reachable'.
### Actual Behavior

iPhone 4 connected to IPv6 network: Both results come up as 'Not Reachable'
iPhone 6s simulator connected to IPv4 network: First result is 'Not Reachable' and second is 'Reachable'
Android 5.1 simulator: Both results come up as 'Reachable'
### Steps to reproduce the Behavior

Run the sample, tap 'Connectivity Test' and look at the results.

**Comment by jamesmontemagno** [comment]
Had a bad merge, please check latest.

**Comment by gviddy** [comment]
Downloaded new version just now. Rebuild, still getting the exact same errors on iOS when running the sample.

**Comment by gviddy** [comment]
Oh and I am downloading the zip of this project, and then unzipping and build, run.

**Comment by jamesmontemagno** [comment]
Oh, of just the samples, they don't have the latest nugets as they are built up for the component. Let me update them.

**Comment by gviddy** [comment]
Yes as in on the github code page I am downloading the zip, unpacking, compiling, and running your sample. Rather than cloning the project in git.

**Comment by jamesmontemagno** [comment]
on iOS the IP will never be reachable as loopback is not enabled on iOS devices, but the second one should be just fine.
