### ISSUE TITLE
TFS character limit reached due obscenely long folder name.

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/ConnectivityPlugin#10]
## Feature Request: rename a folder in the project.

we are seeing a 95 character folder name in the connectivity plugin. can this name please be shortened as it is causing issues with our legacy project and TFS' 259 character limitations.

portable-net45+wp80+wp81+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10+Xamarin.Mac20+UAP10 is the folder name in question. 

Could it be shortened some?

**Comment by jamesmontemagno** [comment]
I have an idea :) Give me a few days.

**Comment by jamesmontemagno** [comment]
They have been shortened. You can now find a custom nuget feed on: https://ci.appveyor.com/nuget/connectivityplugin

New official nuget version will be soon
