### ISSUE TITLE
Abstractions netstandard project using portable PDBs which don't work with UWP

### ISSUE THREAD

**Issue by wes-goulet** [jamesmontemagno/ConnectivityPlugin#101]
## Bug Information
When I add ConnectivityPlugin to my UWP project I lose symbol generation due to [this bug](https://github.com/dotnet/sdk/issues/955).  I know it says closed but it's not actually fixed.  The workaround is to have netstandard projects generate full pdb symbols.  Would be great to update the abstractions project to use full symbols so UWP apps don't lose symbol info when consuming ConnectivityPlugin.

Version Number of Plugin: 3.0.2
Device Tested On: Windows 10 desktop
Simulator Tested On:
Version of VS: 15.3.4
Version of Xamarin: 
Versions of other things you are using:
UWP project targeting creators update, min version anniversary update

### Steps to reproduce the Behavior
- Create a uwp app (mine targets Creators Update but not sure that part matters)
- Reference ConnectivityPlugin nuget
- Build from VS2017 Developer Command prompt `msbuild myapp.sln`

### Expected Behavior
It builds and my uwp app generates symbols

### Actual Behavior
Build fails because it can't generate UWP appx package symbols.

### Screenshots
![image](https://user-images.githubusercontent.com/3293318/30557428-1390f190-9c63-11e7-8784-dcd711826f94.png)

**Comment by prashantvc** [comment]
Merged the pull request #102  for this issue

**Comment by wes-goulet** [comment]
@prashantvc When will this change make it out to the nuget package?

**Comment by prashantvc** [comment]
@wes566 I will talk to James, and get it published as soon as possible

**Comment by prashantvc** [comment]
@wes566 meantime you can download the package from CI server here 
https://ci.appveyor.com/project/JamesMontemagno/connectivityplugin/build/artifacts
