### ISSUE TITLE
Network Bandwidth Change

### ISSUE THREAD

**Issue by MuruganDurai** [jamesmontemagno/ConnectivityPlugin#103]
Hi,  I want to know whether it is possible to get cellular network bandwidth change using 'ConnectivityChanged'  event. Have a requirement to show a toast message when connection's bandwidth is slow. Thanks in advance. Also please let me know to how to get bandwidth for currently connected cellular network?

**Comment by jamesmontemagno** [comment]
It is not possible with the current implementation.
