### ISSUE TITLE
 Visualization Error with Xamarin Live Player

### ISSUE THREAD

**Issue by shinjiDev** [jamesmontemagno/ConnectivityPlugin#105]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.3
Device Tested On: Samsung Galaxy S8
Version of VS: 2017 15.4 Preview 3
Version of Xamarin: Xamarin.Forms. 2.4

### Steps to reproduce the Behavior
I was testing the code of Xamarin University 
MainPage = CrossConnectivity.Current.IsConnected
				? (Page)new NetworkViewPage()
				: new NoNetworkPage();
### Expected Behavior
True or False of "IsConnected"
### Actual Behavior
It's throwing an exception in the device.
### Code snippet
MainPage = CrossConnectivity.Current.IsConnected
				? (Page)new NetworkViewPage()
				: new NoNetworkPage();
### Screenshots
![image](https://user-images.githubusercontent.com/236560/31119917-0952a910-a809-11e7-8c57-aa2f5211ae53.png)

**Comment by jamesmontemagno** [comment]
Please open a bug at: https://bugzilla.xamarin.com/ under Live Player

**Comment by shinjiDev** [comment]
You are right @jamesmontemagno , It's a problem of Live Player.
Regards
