### ISSUE TITLE
Two instances of Wifi connections appearing in connectiontypes collection Android 7.0

### ISSUE THREAD

**Issue by Jhanbury** [jamesmontemagno/ConnectivityPlugin#107]
I have been using the library and found that the ConnectivityChanged event was firing twice for WiFi connections.
I found that the ConnectionTypes collection was registering two sources for a WiFi signal.(See image attached)
I am able to replicate the issue on Android 7 devices.
However I tested it out on a Sony Xperia Z3 with Android 6 - API 23 and could not replicate the issue.

Is this a known issue with Android 7?

## Bug Information

Version Number of Plugin: 3.0.3
Device Tested On: Samsung S7 (Android 7.0 - API 24)
Simulator Tested On: 
Versionof VS:  VS 2017
Version of Xamarin: Forms 2.4.0.282
Versions of other things you are using:

### Steps to reproduce the Behavior
install library run on Android 7 device
### Expected Behavior
single instance of WiFi in collection
### Actual Behavior
two instances of WiFi in collection
### Screenshots
![2017-10-11_10-11-41](https://user-images.githubusercontent.com/11406932/31431890-de536e4c-ae6c-11e7-95b2-cc3c89ac0f09.png)

**Comment by jamesmontemagno** [comment]
Your android device is returning 2 of them. you can call Distinct if you desire.

**Comment by Jhanbury** [comment]
Sorry I should have added that the ConnectionChanged event is being fired twice which is causing issues.
I have tested the scenario across a range of devices and API levels.It seems to be isolated to Android 7 devices in particular. Is there anything that can be done to stop the this?

**Comment by jamesmontemagno** [comment]
it is the device that is firing the events and registering it so nothing i can do. Doesn't happen on my devices.

**Comment by Jhanbury** [comment]
I understand thanks for the help @jamesmontemagno
