### ISSUE TITLE
"This functionality is not implemented in the portable version of this assembly" with Xamarin.droid

### ISSUE THREAD

**Issue by Duraiamuthan** [jamesmontemagno/ConnectivityPlugin#108]
It was throwing the following exception only if its built with 3.0.3 .. I had to downgrade the plugin to 2.3.0 in Droid to make it work. 

 _This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation._

## Bug Information
Version Number of Plugin:3.0.3
Device Tested On:Android Galaxy 5.0.1
Simulator Tested On:
Version of VS: 7.2
Version of Xamarin:4.6.3.4
Versions of other things you are using:
MVVMlight 5.3.0.0

### Steps to reproduce the Behavior
Just add the 3.0.3 plugin in both droid and PCL
Run the project on device and it'll crash upon launch

### Expected Behavior
It should not cause the crash

### Actual Behavior
It crashes the app

### Screenshots
![windowscrash](https://user-images.githubusercontent.com/3798867/31454783-8f8fba76-aeae-11e7-88b9-43626ddf4ab4.png)

**Comment by jamesmontemagno** [comment]
Upgrade all of your nugets
