### ISSUE TITLE
Regression: iOS only returns "other" for connection type

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/ConnectivityPlugin#11]
Please fill out either the bug or feature request section and remove whatever section you are not using.
## Bug

Version Number of Plugin: 2.2.2
Device Tested On: iPhone 6 9.3
Simulator Tested On: iPhone simulator 9.3
### Expected Behavior

Should return wifi if on wifi
### Actual Behavior

Only returning other
### Steps to reproduce the Behavior

Call out to Connection types

**Comment by jamesmontemagno** [comment]
@basdecort89  @artdkmediahuis can you please check: https://www.nuget.org/packages/Xam.Plugin.Connectivity/2.2.3-beta1

**Comment by ghost** [comment]
@jamesmontemagno Tested on iPhone 6 (9.3), iPad Air simulator (8.1 & 9.3), Samsung Galaxy S6 (5.0.0). Seems to be working now. Thanks!

**Comment by jamesmontemagno** [comment]
That is good to know, I added some UnitTests too for the future so that is really good :) 

Had to do with weird IP checking. I assume not many people use the connection types, but glad they are nifty :)

**Comment by ghost** [comment]
Thanks James! Can you tell when this fix will be released?
