### ISSUE TITLE
Is Connected return True in Airplane mode and WiFi is On 

### ISSUE THREAD

**Issue by minafaw** [jamesmontemagno/ConnectivityPlugin#111]
## Bug Information

Version Number of Plugin: 3.3
Device Tested On: iPhone 6 
when I turn air plane on and wifi is on
CrossConnectivity.Current.IsConnected --> return true 
it shouldn't   return true

**Comment by jamesmontemagno** [comment]
Sounds correct... you turned wifi on and connected to Wifi...

**Comment by jamesmontemagno** [comment]
Sounds correct... you turned wifi on and connected to Wifi...
