### ISSUE TITLE
Always return false on IsReachable() or IsRemoteReachable()

### ISSUE THREAD

**Issue by hackzai** [jamesmontemagno/ConnectivityPlugin#112]
When used the Xam.Plugin.Connectivity to test a local WiFi network (without Internet access) and it always return false.

Use Case.
Host a web API server (without require Internet access) in local domain (E.g. 192.168.10.200:8031/api/test). When mobile app (on Android platform) perform the following test always failed.

IsConnected(), because the latest code is test again Internet capability.

So, I changed my code to test against host by IsReachable() as well as IsRemoteReachable() methods call. But, both also return false. Due to in both of this methods it will first call IsConnected().

## Bug Information

Version Number of Plugin: 3.0.3
Device Tested On: Samsung Tablet
Simulator Tested On: NIL
Version of VS: Visual Studio for Mac (Ent) Version 7.2 Build 636
Version of Xamarin: Xamarin Forms 2.4.0.282
Versions of other things you are using: 

### Steps to reproduce the Behavior
Perform IsReachable() or IsRemoteReachable() from mobile app (with mobile data is off) to other server on the same network without Internet access capability.

### Expected Behavior
IsReachable() or IsRemoteReachable() should return true when the given host is valid (with valid ping response)

### Actual Behavior
IsReachable() or IsRemoteReachable() both return false.

**Comment by jamesmontemagno** [comment]
Have you tried out 4.0 beta? I completely re-wrote this logic.

**Comment by hackzai** [comment]
I think should be the same, as in GetIsConnected() method (line # 77 in Android implementation) does check for Internet capability.

     //check to see if it has the internet capability
     if (!capabilities.HasCapability(NetCapability.Internet))
          continue;

**Comment by jamesmontemagno** [comment]
That code doesn't get executed at all when calling IsReachable and IsRemoteReachable. Like I said i re-wrote that full logic.  They don't call IsConnected either.

**Comment by hackzai** [comment]
Code belows are from the Android implementation, showing it will call IsConnected before further test the given host name or port. Perhaps I am wrong.

![screenshot_20171024-071201](https://user-images.githubusercontent.com/2167287/31913683-453b10ba-b88b-11e7-99d7-4523e0df7567.png)

![screenshot_20171024-070041](https://user-images.githubusercontent.com/2167287/31913684-457293d2-b88b-11e7-8105-b4041aaf3a75.png)

**Comment by jamesmontemagno** [comment]
Not in 4.0: https://github.com/jamesmontemagno/ConnectivityPlugin/blob/rechability-updates/src/Connectivity.Plugin.Android/ConnectivityImplementation.cs#L182

https://montemagno.com/connectivity-plugin-4-0-important-and-awesome-changes/

**Comment by hackzai** [comment]
Awesome, I try install beta 4.0 later :)
