### ISSUE TITLE
Current_ConnectivityChanged event is not firing in Xamarin.Forms  Android

### ISSUE THREAD

**Issue by dharamhbtik** [jamesmontemagno/ConnectivityPlugin#113]
I have updated to the latest version (3.0.3) of this plugin and it stops firing the Current_ConnectivityChanged event. Earlier it was working great with version 1.0.0. Below is the code I have written in the MainActivity.cs file

` protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);          
            Plugin.Connectivity.CrossConnectivity.Current.ConnectivityChanged += Current_ConnectivityChanged;
        }`

and the event is as below 
`private void Current_ConnectivityChanged(object sender, Plugin.Connectivity.Abstractions.ConnectivityChangedEventArgs e)
        {
            try
            {               
                if (Plugin.Connectivity.CrossConnectivity.Current.IsConnected)
                {
                     // do work 
                }
                else
                {
                    // show message that you are offline
                }                
            }
            catch (Exception ex)
            {
                //exception handling
            }
        }`

When I debug the code on real device and try to make the device offline (Airoplane mode or turn off the mobile/wifi data) then some time this event fire and most of the time doesn't, 

Its working when I toggle wi-fi

**Comment by jamesmontemagno** [comment]
Did you try to actually test the ConnectivityTypeChanged? that is when the connection type changes.

Else  I can't repro as it works great for me.

**Comment by dharamhbtik** [comment]
connectiontypechanged fired when we changed from cellular to wifi and vice versa. but when we turn off cellular data and turn on again then none of the event calls. i am using 3.0.3 version.

**Comment by jamesmontemagno** [comment]
This most likely mean you are still connected and not actually triggering an event in android that could be monitored.

**Comment by Greg767** [comment]
I do experience something similar with v3.0.3
I start my app with data and wifi deactivated. The app correctly detects the lack of connection. Browser doesn't work neither.
Then I activate only wifi and here I don't get the ConnectivityChanged event at all. Browser  starts to work though so connectivity changes definitely.
As for the ConnectivityTypeChanged event, it fires at startup saying the app is not connected, and it fires as well when I turn the wifi on, but it still says its not connected.

Thanks!

**Comment by ZhangMaKe** [comment]
+1 Greg767.  Starting the app with wifi on IsConnected is true.  Going from no connection to wifi only doesn't trigger event, but going from no connection to data fires the event.

**Comment by ravikanasagra1** [comment]
I have plugin 3.3.0 and on Xamarin Android application, it does not trigger the connectivity changed event on android OS 8.0 device. I tried for Network internet & WiFi Internet.

**Comment by WilliamWatterson86** [comment]
@ravikanasagra1 - same issue for me on Android 8.0 - were you able to find a solution?

**Comment by ravikanasagra1** [comment]
No, William. I had used native code using broadcast listener for connectivity/network change.

**Comment by jamesmontemagno** [comment]
There are two different types of broadcasts... a general internet connection change and also a type change for network changing. You can also try https://github.com/xamarin/essentials which has a single event.

**Comment by ravikanasagra1** [comment]
is it ok to use Xamarin Essentials? This link https://docs.microsoft.com/en-us/xamarin/essentials/ says that it is in pre-release mode. It this production ready?

**Comment by jamesmontemagno** [comment]
It is pre-release so the APIs may change and there may be bugs as we are testing, but I use it personally. I am interested if the code there works for you to fix this bug as I use very similar code.
