### ISSUE TITLE
Device connected to WiFi router without Internet access

### ISSUE THREAD

**Issue by abrasat** [jamesmontemagno/ConnectivityPlugin#115]
If an Android device is connected via WiFi to a router that does not have Internet access, CrossConnectivity.Current.IsConnected  is still returning true. Is there a better way to check if Internet is available or not ?

**Comment by jamesmontemagno** [comment]
Yup, that is correct based on the device type. You can try to ping a remote server too.

**Comment by abrasat** [comment]
Thanks, I solved it by using the IsRemoteReachable() method.
Is there any "RemoteReachabilityChanged" event available in the plugin, similar to the ConnectivityChanged event ? Or how else can the application be triggered when the internet reachability changes ?

**Comment by jamesmontemagno** [comment]
there is not as it is a costly operation and not events to loop into.
