### ISSUE TITLE
CrossConnectivity.Current.IsConnected returns true on a router with no connection

### ISSUE THREAD

**Issue by pumaprog** [jamesmontemagno/ConnectivityPlugin#118]
## Bug Information

Version Number of Plugin:  3.0.3
Device Tested On: iPad 5th Generation iOS11
Simulator Tested On:
Version of VS: Community 2015, Version 14.0.2 Update 3
Version of Xamarin: 4.7.10.38
Versions of other things you are using:

### Steps to reproduce the Behavior
I have connected my debugger and my device to a network with no internet connection, so there is a _network_ connection, but no _internet_.  Added bool res = CrossConnectivity.Current.IsConnected; to Init method.
### Expected Behavior
IsConnected returns false.
### Actual Behavior
IsConnected returns true.
### Code snippet
bool res = CrossConnectivity.Current.IsConnected

**Comment by jamesmontemagno** [comment]
Duplicate: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/115
