### ISSUE TITLE
WPF/netstandard: This functionality is not implemented in the portable version of this assembly.

### ISSUE THREAD

**Issue by gmwilhelm** [jamesmontemagno/ConnectivityPlugin#119]
Hello,

i'm trying to use this plugin in a class library that targets net461 and netstandard 1.6. My class library then will be used in a wpf project and a netcore console application.

Referencing the plugin nuget works, but when use the plugin, i get this message:

> This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

Just adding the nuget also to the console app didn't work.

What do i have to do to get rid of this message?

Regards,
  Dirk

**Comment by jamesmontemagno** [comment]
You need to include it in all projects. Ensure that the references that are included in the actual WPF app are from lib/net45 as there are 2 that get bundled.

**Comment by jamesmontemagno** [comment]
[App.zip](https://github.com/jamesmontemagno/ConnectivityPlugin/files/1483691/App.zip)

Works just fine

**Comment by gmwilhelm** [comment]
Thanks for that sample.

But this console app  doesn't work:

[ConsoleApp1.zip](https://github.com/jamesmontemagno/ConnectivityPlugin/files/1484422/ConsoleApp1.zip)

**Comment by jamesmontemagno** [comment]
Correct, it does not support .net core apps currently. Just the main frameworks.

**Comment by jamesmontemagno** [comment]
you can try any of the new beta packages and they now have .net core support

**Comment by gmwilhelm** [comment]
I tried the new 4.0.0-beta164 but i still get that error.

**Comment by jamesmontemagno** [comment]
Yeah I am working on the packaging, .NET Core works a bit weird

**Comment by gmwilhelm** [comment]
4.0.0-beta167 works. Thank you very much.

**Comment by gmwilhelm** [comment]
Sorry to bother you again with this, but maybe you can take a look at this console app again?

I'm getting this error with it:

> Could not load file or assembly 'Plugin.Connectivity, Version=4.0.167.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

[ConsoleApp1.zip](https://github.com/jamesmontemagno/ConnectivityPlugin/files/1487046/ConsoleApp1.zip)

**Comment by jamesmontemagno** [comment]
Yup yup on it
