### ISSUE TITLE
ConnectivityTypeChanged not firing after adding handlers to the disposed service again

### ISSUE THREAD

**Issue by behzad62** [jamesmontemagno/ConnectivityPlugin#122]
This bug is happening with Xamarin android

## Bug Information

Version Number of Plugin: 3.0.3
Device Tested On: Galaxy tab s2
Simulator Tested On: -
Version of VS: Visual studio 2017
Version of Xamarin: 4.7.10.38
Versions of other things you are using:
windows 10(Build 10 16299)
MvvMcross 5.4.2

### Steps to reproduce the Behavior
Dispose the service and re subscribe to it's events after.
### Expected Behavior
Either thorw object disposed exception or properly invoke registered event handlers after service is disposed and accessed again.
### Actual Behavior
ConnectivityChanged and ConnectivityTypeChanged events handlers not firing after resubscribing to the disposed service.

**Comment by jamesmontemagno** [comment]
Code sample please that is reproducable

**Comment by behzad62** [comment]
protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            // Set our view from the "main" layout resource
            SetContentView(Resource.Layout.Main);
            textView = FindViewById<TextView>(Resource.Id.textView1);

        }

        protected override void OnStart()
        {
            base.OnStart();
            textView.Text = string.Empty;
            CrossConnectivity.Current.ConnectivityTypeChanged += Current_ConnectivityTypeChanged;
        }

        private void Current_ConnectivityTypeChanged(object sender, Plugin.Connectivity.Abstractions.ConnectivityTypeChangedEventArgs e)
        {
            string connections = string.Empty;
            foreach (var item in e.ConnectionTypes)
            {
                connections += item.ToString() + " | ";
            }
            textView.Text = connections;
        }

        protected override void OnStop()
        {
            base.OnStop();
            CrossConnectivity.Current.ConnectivityTypeChanged -= Current_ConnectivityTypeChanged;
           
            CrossConnectivity.Current.Dispose();
        }

**Comment by behzad62** [comment]
Simple xamarin-android project with above code in the MainActivity will do for me.

**Comment by jamesmontemagno** [comment]
You want to call: CrossConnectivity.Dispose();  not CrossConnectivity.Current.Dispose();

**Comment by behzad62** [comment]
Yes thanks. That solved the issue. Thought, the sample in the docs:
`using(var connectivity = CrossConnectivity.Current)
    {
        return connectivity.IsConnected;
    }`
was a bit misleading. I thought, I should call the dispose method on the current instance.

**Comment by jamesmontemagno** [comment]
updated docs :)

**Comment by EmilAlipiev** [comment]
Isnt calling dispose() expensive? should we wrap around using instead or it is not possible since Plugin.Connectivity.CrossConnectivity.IsSupported is static? So below is not best usage without Dispose?

```
if (!Plugin.Connectivity.CrossConnectivity.IsSupported)
                {            
                    return false;
                }

                using (var current = Plugin.Connectivity.CrossConnectivity.Current)
                {
                    

                    if (current.IsConnected == false)
                    {
                        IsConnected = false;
                        return false;
                    }
                    else
                    {
                        if (await current.IsRemoteReachable("someurl") == false)
                        {
                            IsConnected = false;
                            return false;
                        }

                    }
                }             
```
