### ISSUE TITLE
UWP devices not supported

### ISSUE THREAD

**Issue by MaxiPigna** [jamesmontemagno/ConnectivityPlugin#124]
I am using the plugin to check connectivity on a Xamarin app targeting UWP, but none of my devices seems to be supported.

## Bug Information

Version Number of Plugin: 3.0.3
Device Tested On: 
- Lumia 950 Windows 10 Mobile Build 10.0.15254.1
- Lenovo Yoga X1 Windows 10 Build 16299.19

Version of VS:  2017
Version of Xamarin: 2.4.0.91020

### Steps to reproduce the Behavior

1. Create a simple Xamarin App
2. Add the property I defined below
3. Start the app with the phone connected
4. Switch the phone to Flight Mode
5. Test connectivity

### Expected Behavior
IsConnected = false

### Actual Behavior
IsConnected=true due to the fact that CrossConnectivity.IsSupported returns false
### Code snippet
This is the property I have defined in the App.xaml.cs file.
`
public static bool IsConnected
{
    get
			{
                if (!CrossConnectivity.IsSupported)
				{
					Debug.WriteLine("INFO: Connectivity check failed, platform not supported.");
					return true;
				}
				return CrossConnectivity.Current.IsConnected;
			}
		}`

I always fall into the IF

**Comment by jamesmontemagno** [comment]
Did you install the nuget into your UWP app?

**Comment by MaxiPigna** [comment]
Shame on me... Thank you for your quickness!
