### ISSUE TITLE
IsRemoteReachable(string, int, int) vs IsRemoteReachable(uri)

### ISSUE THREAD

**Issue by gmwilhelm** [jamesmontemagno/ConnectivityPlugin#125]
Hello,

when i use 

`var isHostReachable = await CrossConnectivity.Current.IsRemoteReachable("http://www.github.com");`

i get this warning:

> 'IConnectivity.IsRemoteReachable(string, int, int)' is obsolete: 'This method is now obsolete and replaced with IsRemoteReachable that take in a full Uri. This method will be removed in future revisions.'

But when i try to use 

```
var uri = new Uri("http://www.github.com");
var isHostReachable = await CrossConnectivity.Current.IsRemoteReachable(uri);
```
i get this error:

> Argument 1: cannot convert from 'System.Uri' to 'string'

Version Number of Plugin: 4.0.0.171-beta
Device Tested On: Windows 10 NetCore Console app
Version of VS: 15.4.5

**Comment by prashantvc** [comment]
You're missing `timeout` parameter in `IsRemoteReachable` method.

For example, it should looks something like:

```csharp
var uri = new Uri("http://www.github.com");
var isHostReachable =  CrossConnectivity.Current
    .IsRemoteReachable(uri, TimeSpan.FromSeconds(5));
```
