### ISSUE TITLE
Android: Plugin.Connectivity.Abstractions.IConnectivity.IsRemoteReachable not found.

### ISSUE THREAD

**Issue by gmwilhelm** [jamesmontemagno/ConnectivityPlugin#129]
Hello,

on Android i get this error message:

> System.MissingMethodException: Method 'Plugin.Connectivity.Abstractions.IConnectivity.IsRemoteReachable' not found.

This code works (but is marked deprecated):

`var isHostReachable  = await CrossConnectivity.Current.IsRemoteReachable("http://www.github.com");`

this code throws the error message:
```
var uri = new Uri("http://www.github.com");
var isHostReachable = await CrossConnectivity.Current.IsRemoteReachable(uri, TimeSpan.FromSeconds(5));
```

Version Number of Plugin: 4.0.0.171-beta
Simulator Tested On: Visual Studio Emulator for Android 6.0, Api23
Version of VS: VS2017 15.5
Version of Xamarin: 2.5.0.91635

**Comment by jamesmontemagno** [comment]
Did you update all your nugets, maybe uninstall and reinstall..
