### ISSUE TITLE
System.NotImplementedException

### ISSUE THREAD

**Issue by quycao** [jamesmontemagno/ConnectivityPlugin#13]
CrossConnectivity.Current.IsConnected get 'System.NotImplementedException' in Plugin.Connectivity.DLL  on every platforms

var IsNetworkReachable = CrossConnectivity.Current.IsConnected;

Version Number of Plugin: 2.2.12.0
Device Tested On: 
Simulator Tested On: Android, Windows 10 Mobile, Windows 10

**Comment by jamesmontemagno** [comment]
Did you install the NuGet into all of your projects?

**Comment by stroborobo** [comment]
For the record:

I got this message as well, the package is installed in both the base project and the platform projects. However it failes on iOS, but not on Android. The reference is there, too, for both Plugin.Connectivity and Plugin.Connectivity.Abstractions. Also this seemed to appear kinda randomly as everything was working perfectly yesterday and I didn't change anything around this. Re-installing all the Xam.Plugin.\* packages in all projects helped and it's working again now.
