### ISSUE TITLE
App freezes while switching to Airplane mode from WIFI/cellular data and vice versa in iOS devices.

### ISSUE THREAD

**Issue by SudharsanKrishnamoorthy** [jamesmontemagno/ConnectivityPlugin#130]
## Bug Information

Version Number of Plugin:3.0.3
Device Tested On:  Iphone devices
Simulator Tested On: 
Version of VS: 14.0.25123.00.update 2
Version of Xamarin: 6.1.5(build 0)
Versions of other things you are using:

### Steps to reproduce the Behavior:
1.Open the app with active internet connection cellular data / WIFI. (Iphone 7)
2.Switch to Airplane mode, wait for the app to respond.(Keep a label to display the network state)
3.Again switch off the Airplane mode wait for the label to change.
4.Repeat the steps for some time.
5.App freezes at some point.

### Expected Behavior
The "ConnectivityTypeChangedEventArgs" should be invoked only once if the device is switched to Airplane mode and vice versa.
### Actual Behavior
The "ConnectivityTypeChangedEventArgs" is invoked more than 2 times and it takes so much of time to complete the invocations. So the app waits until all the invocations gets completed. This makes the app to freeze.

**Comment by jamesmontemagno** [comment]
Seems like events are firing and your app code has some issues making it freeze.
