### ISSUE TITLE
Java.Lang.ClassNotFoundException: Didn't find class ConnectivityChangeBroadcastReceiver

### ISSUE THREAD

**Issue by mo-kml** [jamesmontemagno/ConnectivityPlugin#131]
Java.Lang.ClassNotFoundException: Didn't find class "md55acd92097db1193d6a1e7330cb14252a.ConnectivityChangeBroadcastReceiver" on path: DexPathList[[zip file "/data/app/cas.calock.apps.android-1/base.apk"],

I have to Publish today and i have no idea what should i do. it was working perfectly and somehow after rebuild it got stop working
any ideas?
ive tested multiple versions but still got this error

## Bug Information

Version Number of Plugin: 4.0.0.171-beta
Device Tested On: 6.0
Simulator Tested On: 7.1.1
Version of VS: 15.5.0
Version of Xamarin: 2.5.0.121934

**Comment by prashantvc** [comment]
Could you share the complete build output and Exception stack trace? It will help us to troubleshoot the issue

**Comment by lantonello** [comment]
Same for me.
How I can get the complete build output and Stack Trace? Sorry, I'm a Xamarin newbie.

**Comment by prashantvc** [comment]
@lantonello you can find the instructions here https://developer.xamarin.com/guides/cross-platform/troubleshooting/questions/version-logs/#debug-logs-for-xamarin-apps

**Comment by JonDouglas** [comment]
This should be resolved via https://github.com/xamarin/xamarin-android/pull/1142 which will be included in a future build.

**Comment by jamesmontemagno** [comment]
Is there a workaround @JonDouglas I haven't seen this at all. Do people just need to do a clean/rebuild?

**Comment by JonDouglas** [comment]
@jamesmontemagno https://bugzilla.xamarin.com/show_bug.cgi?id=61073#c40 has a workarond, ensure to "unblock" the dll after downloading via properties!
