### ISSUE TITLE
Samsung S7 Edge - ConnectivityChanged not firing after reconnecting

### ISSUE THREAD

**Issue by Springham** [jamesmontemagno/ConnectivityPlugin#134]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.3
Device Tested On: Samsung S7 Edge (Android 7.0)
Version of VS: VS 4 Mac - 7.3.2
Version of Xamarin: Xamarin.Android - 8.1.0.25
Versions of other things you are using:
Android SDK Tools: 26.1.1
Android SDK Platform Tools: 26.0.2
Android Build Tools: 27.0.1

### Steps to reproduce the Behavior
Subscribe to a ConnectivityChanged event but do not unsubscribe.
Enter Airplane Mode and wait for ConnectivityChanged event to fire
Exit Airplane Mode

### Expected Behavior
ConnectivityChanged event also fires after exiting Airplane Mode

### Actual Behavior
It doesn't fire

### Code snippet
_connectivity.ConnectivityChanged += (sender, e) => 
{
      // Do Something
};

### Screenshots
N/A

### Notes
- I've tried it on other devices such as the Samsung S8 with no issue whatsoever.
- The internet is reconnecting because I can make successful requests after exiting Airplane mode

**Comment by AndreiMisiukevich** [comment]
We faced with the same behavior too.

**Comment by fraedom-lkwong** [comment]
It looks like under the connectivityImplementation is consuming it.

`							//if on 23+ then we can also check validated
							//Indicates that connectivity on this network was successfully validated.
							//this means that you can be connected to wifi and has internet
							if ((int)Android.OS.Build.VERSION.SdkInt >= 23 && !capabilities.HasCapability(NetCapability.Validated))
								continue;`

Should that part be returning true? if it has wifi and internet then it is connected?

**Comment by fraedom-lkwong** [comment]
Tested this on S7(Not edge)

Same as https://github.com/jamesmontemagno/ConnectivityPlugin/issues/142
