### ISSUE TITLE
When the phone is locked the app crashes when you run CrossConnectivity.Current.IsConnected

### ISSUE THREAD

**Issue by o-stepanov** [jamesmontemagno/ConnectivityPlugin#135]
## Bug Information
When the phone is locked the app crashes
when you run CrossConnectivity.Current.IsConnected. Maybe I'm doing something wrong myself. I run the repeating method in Task.Factory.StartNew ().

Version Number of Plugin:3.0.3
Device Tested On:iPhone SE 11.1.1

**Comment by jamesmontemagno** [comment]
Would need a repro project

**Comment by jamesmontemagno** [comment]
Do you have the code you are running, would like to see what you are doing in that task.

**Comment by o-stepanov** [comment]
sorry that did not answer immediately. We use it in the design of the basic project and therefore the project can not give it completely. I'll try to collect a clean project and check whether there is the same problem there.

**Comment by KIzotov** [comment]
I have the same problem in my project
I can not find the exact reason, but I suspect that the problem is possible in the same connection check
I'll gather more data and unloaded here
