### ISSUE TITLE
App Crashes All The Time

### ISSUE THREAD

**Issue by jonathan-austen** [jamesmontemagno/ConnectivityPlugin#136]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.3
Device Tested On: 
Simulator Tested On: Android Emulator API25
Version of VS: 2017 PRO
Version of Xamarin: latest
Versions of other things you are using:

### Steps to reproduce the Behavior
Created this function and when I call it, the emulator crashes.

        public bool IsConnected()
        {
            if (!CrossConnectivity.IsSupported)
                return true;

            if (!CrossConnectivity.Current.IsConnected)
                return false;   
            else
                return true;
        }
### Expected Behavior
App should not crash.
### Code snippet

        public bool IsConnected()
        {
            if (!CrossConnectivity.IsSupported)
                return true;

            if (!CrossConnectivity.Current.IsConnected)
                return false;   
            else
                return true;
        }

**Comment by jamesmontemagno** [comment]
What is the stack trace?

**Comment by jonathan-austen** [comment]
There is no stack trace. The app just says it's quitting and the error in Visual Studio is:

Java.Lang.ClassNotFoundException: <Timeout exceeded getting exception details>

**Comment by jamesmontemagno** [comment]
Yes, read this: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/131

**Comment by jamesmontemagno** [comment]
The work around would be to get the latest xamarin fixes or to remove the custom application class i add and manually set the current activity.

**Comment by jonathan-austen** [comment]
Well, I'm sure I have the latest xamarin fixes and the other part I don't know what to do.  I'll just use someone else's code that isn't so buggy.

**Comment by jamesmontemagno** [comment]
This has to do with an issue in Xamarin.Android itself and not with my code. I don't appreciate comments like that.
