### ISSUE TITLE
Android Cellular Issue

### ISSUE THREAD

**Issue by Seddy24** [jamesmontemagno/ConnectivityPlugin#138]
## Bug Information

Version Number of Plugin: 3.0.03
Device Tested On: Moto Z Play (Android 7.1 API 25)
Simulator Tested On: N/A
Version of VS: 2017 Pro - 15.5.2
Version of Xamarin: 4.8.0.753
Versions of other things you are using:

### Steps to reproduce the Behavior
Enable Wifi and start up app,  Cellular not in list.  
Close App and disable Wifi, re-open app, Cellular in list.
Leave App open and turn of Wifi, Cellular in list.

### Expected Behavior
Cellular should be in the list of ConnectionTypes regardless of Wifi state

### Actual Behavior
Cellular not in list of ConnectionTypes, only Wifi shows up.

### Code snippet
if(CrossConnectivity.Current.ConnectionTypes.Any(c => c == ConnectionType.Cellular)){
{
// open phone 
}

**Comment by jamesmontemagno** [comment]
That is because it is not active and Android is exclusively using WiFi. This is expected.

See: https://github.com/jamesmontemagno/ConnectivityPlugin/blob/master/src/Connectivity.Plugin.Android/ConnectivityImplementation.cs#L243

**Comment by Seddy24** [comment]
@jamesmontemagno Do you know of a way to verify cellular is available even when Wifi is enabled for Android?  I want to prevent the user from doing something if they can't make a phone call.
