### ISSUE TITLE
Trigger ConnectivityChanged Event every time the ConnectionTypes change

### ISSUE THREAD

**Issue by sourceclimber** [jamesmontemagno/ConnectivityPlugin#14]
## Feature Request:

The ConnectivityChanged event should be triggert every time the Connection Type changes.
E.g. if i am in a Cellular Network and switch to a WiFi network, i would like to get notified that the connection type changed.

Because the IsConnected status does not change when switching from one ConnectionType to another, the event is not triggert. This could be enabled by removing the check if the previous connection status is the same as the new connection status, for example:
- On Android in ConnectivityChangeBroadcastReceiver.cs line 78.
- On iOS in ConnectivityImplementation.cs on line 50.

Another possibility would be to introduce a ConnectionTypeChanged event.

**Comment by sourceclimber** [comment]
I added a ConnectivityTypeChanged event if someone wants to test it: https://github.com/haknode/ConnectivityPlugin
Should i send you a pull request for this?

**Comment by jamesmontemagno** [comment]
Yes, please do into the dev branch :)
