### ISSUE TITLE
CrossConnectivity.Current.ConnectivityTypeChanged is getting fired when app goes in background for the first time.

### ISSUE THREAD

**Issue by Mohit-Kharbanda** [jamesmontemagno/ConnectivityPlugin#140]
CrossConnectivity.Current.ConnectivityTypeChanged is getting fired when Xamarin iOS app goes in background for the first time after app is launched. There are no connection changes that are being done, neither the WiFi is switched on or off nor the WiFi is changed from one connection to another.

Is this event triggered by purpose in such case (first time app moving to background) or is this needs some kind of fix?

**Comment by devopsone** [comment]
Also happens under Android. I de/register HandleConnectivityChanged & HandleConnectivityTypeChanged in onSleep and onResume of the app object but it never gets fired after i launch the app. If i send the app once to the background and bring it back everything works fine.
