### ISSUE TITLE
UWP cannot load 3.1.1. version of the plugin

### ISSUE THREAD

**Issue by EGoverde** [jamesmontemagno/ConnectivityPlugin#141]
## Bug Information

Version Number of Plugin: 3.1.1.
Device Tested On: Windows 10 Desktop (up-to-date)
Simulator Tested On: None
Version of VS: Enterprise 2017 15.5.6
Version of Xamarin: None (on Windows)
Versions of other things you are using:

### Steps to reproduce the Behavior
Making a call to CrossConnectivity.Current.IsConnected from the PCL project. Same exact code works when downgrading to the previous 3.0.3. Target framework is 'uap10.0.10240'.

### Expected Behavior
Returning either True or False.

### Actual Behavior
Exception occurs. Output is: Could not load file or assembly 'Plugin.Connectivity, Version=3.1.1.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by jamesmontemagno** [comment]
Make sure you uninstall and re-install and also do a full clean and rebuild.

Check to make sure it is referencing the correct version.

**Comment by prashantvc** [comment]
Please reopen if you continue to have any issues referencing the plugin

**Comment by EGoverde** [comment]
Uninstalling, removing the /bin, /obj, and /packages folder did the trick in the end. Thanks.
