### ISSUE TITLE
Network is connected but validate is false

### ISSUE THREAD

**Issue by achievecreative** [jamesmontemagno/ConnectivityPlugin#142]
I'm new to the mobile development, also new to the Xamarin. I try to use this plugin on Android to check network capability, but it always return false, not matter on simulator or my nextus 9.

After some debug, I found the following possible the issue.

https://github.com/jamesmontemagno/ConnectivityPlugin/blob/master/src/Connectivity.Plugin.Android/ConnectivityImplementation.cs

`							if ((int)Android.OS.Build.VERSION.SdkInt >= 23 && !capabilities.HasCapability(NetCapability.Validated))`

The **capabilities.HasCapability(NetCapability.Validated)** always return false on my simulator and real device, and i'm 100% sure my device has internet.

I think we should continue check the network info if HasCapability(NetCapability.Validated) return false.

## Bug Information

Version Number of Plugin: 3.1.1 and 4.0.0.171-beta
Device Tested On: Nexus 9 with Android 7.1
Simulator Tested On: Simulator(Android 7.1 API 25)
Version of VS: 2017.5
Version of Xamarin: 4.8.0.760
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
If this returns false it means: https://developer.android.com/reference/android/net/NetworkCapabilities.html#NET_CAPABILITY_VALIDATED

Works fine on my emulators. Are you on some sort of VPN or something?

**Comment by jamesmontemagno** [comment]
Changing this could directly impact:
Implement fixes for #56, #96, #95, #90

**Comment by achievecreative** [comment]
@jamesmontemagno Emulator not, but nexus 9 yes, i have connect to the VPN.

As my understand, validate means has Internet connection, but invalidate doesn't means no internet connection.

**Comment by achievecreative** [comment]
I checke my device again, i saw it said "Network may be monitored". Maybe this is the issue.

**Comment by fraedom-lkwong** [comment]
I had a quick look and it seems that it will enter it while its in a state where it is connected but hasn't validated it before checking the wifi status. A delay seems to make it work for a Pixel/S7 although android does not seem to trigger a connectivity change.

It seems only reproducible on a real device for me as you need WIFI.

On the pixel its not 100% but samsung S7 is more consistent.

**Comment by fraedom-lkwong** [comment]
When will this be released in an official release?
