### ISSUE TITLE
CrossConnectivity.Current.IsConnected produces starting and finishing tasks on XAMARIN.Android

### ISSUE THREAD

**Issue by Schullebernd** [jamesmontemagno/ConnectivityPlugin#144]
Hello, maybe it's a normal behavior but I think it isn't. As written in the headline. After calling CrossConnectivity.Current.IsConnected the first time, the app starts and finishes task constantly.
Is it a bug or a feature?

Thanks for your support!
Marcel 

## Bug Information

Version Number of Plugin: 3.1.1
Device Tested On: Android 7.0 (ZTE BLADE V8 MINI)
Simulator Tested On: not tested
Version of VS: 15.6 Preview 6
Version of Xamarin:
XAMARIN - 4.9.0.748
XAMARIN.Android SDK - 8.2.0.15
Versions of other things you are using: 
Compile using Android Version 7.1
Min Android Version 5.0 (API Level 21)
Target Android Version 7.1 (API Level 25)

### Steps to reproduce the Behavior
Create a new XAMARIN.Android project.
Simply call CrossConnectivity.Current.IsConnected in an Activity (e.g. after clicking on a button).

### Expected Behavior
The component should only return the internet connection status.

### Actual Behavior
Everthing works good, but the application constantly produces starting and finishing threads after callng the IsConnected  member.
You can see this in the console. Here are some examples (unfortunately in german):
`Thread finished: <Thread Pool> #4
Der Thread 0x4 hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #3
Thread started: <Thread Pool> #7
Der Thread 0x3 hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #6
Der Thread 0x6 hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #5
Thread started: <Thread Pool> #8
Der Thread 0x5 hat mit Code 0 (0x0) geendet.
Thread started: <Thread Pool> #9
Thread finished: <Thread Pool> #7
Thread started: <Thread Pool> #10
Der Thread 0x7 hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #8
Der Thread 0x8 hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #10
Thread started: <Thread Pool> #11
Der Thread 0xa hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #9
Thread started: <Thread Pool> #12
Thread started: <Thread Pool> #13
Der Thread 0x9 hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #12
Der Thread 0xc hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #11
Thread started: <Thread Pool> #14
Der Thread 0xb hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #13
Thread started: <Thread Pool> #15
Thread started: <Thread Pool> #16
Der Thread 0xd hat mit Code 0 (0x0) geendet.`

### Code snippet
-
### Screenshots
-

**Comment by jamesmontemagno** [comment]
What does your code look like? I start no threads

**Comment by Schullebernd** [comment]
It's quite simple.
I have a very simple Activity:
```using System;
using System.Threading.Tasks;
using Android.App;
using Android.OS;
using Android.Widget;
using Plugin.Connectivity;
using Schiessbuch.Model.Service;

namespace Schiessbuch.Droid
{
    [Activity(Label = "RestServiceActivity")]
    public class RestServiceActivity : Activity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            // Set our view from the "main" layout resource
            SetContentView(Resource.Layout.RestService);

            Button testButton = FindViewById<Button>(Resource.Id.TestButton);
            TextView restTextView = FindViewById<TextView>(Resource.Id.RestTextView);

            testButton.Click += async (sender, e) =>
            {
                if (CrossConnectivity.Current.IsConnected)
                {
                    // Code is commented out. So I found out, that the issue starts with calling IsConnected only
                }
                else
                {
                    Toast.MakeText(this, "Keine Internetverbindung verfügbar!", ToastLength.Long).Show();
                }
            };
        }
    }
}```

**Comment by jamesmontemagno** [comment]
No issues for me here or with the plugin.
