### ISSUE TITLE
Adding cordova-plugin-vpn getting error!!!

### ISSUE THREAD

**Issue by srimathselva** [jamesmontemagno/ConnectivityPlugin#147]
I have trying to adding **plugin (cordova-plugin-vpn)** to ionic framework for developing hybrid mobile application. unfortunately getting the following error. 

**ERROR ::**
Installing "cordova-plugin-geolocation" for android
Installing "com.aquto.cordova.VPNManager" for android
Failed to install 'com.aquto.cordova.VPNManager': Error: Variable(s) missing: ALLOWWIFI
   
(node:30762) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Variable(s) missing: ALLOWWIFI

**Must appreciation for the solution**

**Comment by jamesmontemagno** [comment]
This isn't a cordova plugin.
