### ISSUE TITLE
Adding cordova-plugin-vpn plugin from following command cordova plugin add cordova-plugin-vpn. but getting error!!! 

### ISSUE THREAD

**Issue by srimathselva** [jamesmontemagno/ConnectivityPlugin#148]
I have trying to adding plugin (cordova-plugin-vpn) to ionic framework for developing hybrid mobile application. unfortunately getting the following error.

**ERROR:**
(node:32320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Variable(s) missing (use: --variable ALLOWWIFI=value).

Thanks !!!

**Comment by jamesmontemagno** [comment]
This isn't a cordova plugin.

**Comment by srimathselva** [comment]
Thanks @jamesmontemagno.  Can you suggest me to add correct cordova vpn plugin to ionic framework.
