### ISSUE TITLE
Detect a VPN switching On/Off

### ISSUE THREAD

**Issue by RuddyOne** [jamesmontemagno/ConnectivityPlugin#155]
This issue needs label "Question".

Just a quick question about this plugin. I use AirWatch to push my applications out and some use a VPN (AirWatch Tunnel). When you open the application the VPN then triggers to start (with a second or two delay).

I do not seem to get a event raised for `ConnectivityChanged` when the VPN is switched on? Not sure if this is a bug or the plugin is not designed to handle this type of situation.

**Comment by jamesmontemagno** [comment]
This is not possible no. Even checking VPN settings on each is a bit hard. But I will leave this on to see if I can detect in the future.

**Comment by bigcoops** [comment]
Have you tried using 'IsRemoteReachable' to test the availability of a host that is only accessible when the VPN in turned on?
