### ISSUE TITLE
ConnectivityChanged doesn't fire

### ISSUE THREAD

**Issue by Ying1986** [jamesmontemagno/ConnectivityPlugin#16]
## Bug

Version Number of Plugin: 2.2.12
Device Tested On: iPhone 6 (iOS 9.3.2)
Simulator Tested On: NO
### Expected Behavior

**ConnectionChanged** delegated is fired when I make iPhone online/off-line.
### Actual Behavior

**ConnectionChanged** is not called, and `CrossConnectivity.Current.IsConnected` is always true if call manually.

**Comment by jamesmontemagno** [comment]
should be fixed in latest beta, have been testing it out and works well.
