### ISSUE TITLE
iOS and IPV6 network

### ISSUE THREAD

**Issue by acaliaro** [jamesmontemagno/ConnectivityPlugin#164]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.2.0
Device Tested On: iphone 6
Simulator Tested On:
Version of VS: VS4MAC 7.5.1
Version of Xamarin: XF 2.3.4

Xamarin.iOS
Version: 11.10.1.178 (Visual Studio Community)
Hash: 408d3574
Branch: d15-7
Build date: 2018-05-08 18:56:30-0400
Versions of other things you are using:

### Steps to reproduce the Behavior
Create a IPV6 network as described in http://www.brianjcoleman.com/tutorial-how-to-test-your-app-for-ipv6-compatibility/

Connect the iphone to this IPV6 network

Excecute in Xamarin Forms this code:

                                                  string myip = "https://95.255.46.220/crmf"
						var ip = new Uri(myip).Host;
						var port = new Uri(myip).Port;

						var isReachable = await CrossConnectivity.Current.IsRemoteReachable(ip, port);
						if(isReachable == false) {
							await DisplayAlert("ERROR", "ERROR", "Ok");
							return;
						}

### Expected Behavior

I expect that remote server is reacheable under a IPV6 network

### Actual Behavior
Server is unreachable. On a non IPV6 network, the server is reachable

### Screenshots

@jamesmontemagno maybe not a "plugin" command, but I would like to know why this IP is not reachable...

**Comment by jamesmontemagno** [comment]
You could try the 4.0.0 package however I do not even really recommend using IsRemoteReachable at all. Just try to make the web request.

**Comment by acaliaro** [comment]
Thanks @jamesmontemagno 
Web request fails the same… which can be the problem with a xxx.xxx.xxx.xxx ip when I use a IPV6 network? There is a solution for this? It's only on iOS

**Comment by jamesmontemagno** [comment]
not sure, i mean you would want to find the IPV6 address perhaps. I wouldn't use an IP unless you are in a network that requires it and in general. I had a blog here: https://blog.xamarin.com/making-your-ios-apps-ipv6-ready/
