### ISSUE TITLE
Android - CrossConnectivity.Current.IsRemoteReachable return true when the wifi router doesn't connect to Internet 

### ISSUE THREAD

**Issue by ewoody** [jamesmontemagno/ConnectivityPlugin#165]
CrossConnectivity.Current.IsRemoteReachable() returns True on Android devices( from Sony, Google Pixel, Huawei and Samsung) when the WiFi is enabled but not connected to the Internet yet. (I have not input the username and password in WiFi connection promote so that the connection is not set up yet)

Version Number of Plugin:
4.0.0.190

Device Tested On:
Samsung Galaxy S9

Version of VS: 
Visual Studio for Mac, 7.6.7 (build 49)

Version of Xamarin:
3.2.0.839982

### Expected Behavior
Android - return False when the WiFi is not connected to Internet and the device doesn't have a SIM card.

### Actual Behavior
return ture

### Code snippet
 CrossConnectivity.Current.IsRemoteReachable("www.google.com");

Same issue as #89

**Comment by jamesmontemagno** [comment]
Same as #89 as noted and not fixing as it can't be done.
