### ISSUE TITLE
Error due to unknown "NetworkInterfaceType"

### ISSUE THREAD

**Issue by behzad62** [jamesmontemagno/ConnectivityPlugin#166]
Version Number of Plugin: 3.2
Device Tested On: Windows 10
Version of VS: 2017
Versions of other things you are using:
 Wpf app using .net 4.6.1
 
In the .net45 implementation (I didn't check others)," ConnectivityImplementation" constructor calls ResetConnections method which iterates on all network interfaces and throws ArgumentOutOfRangeException at the line '123' in a case of default "NetworkInterfaceType". I found out that some VPN apps might create network interfaces with unorthodox "NetworkInterfaceType" (i.e. number 53). In such a cases which are out of developer's control the Connectivity instance will fail to init, hence, plugin will be unusable. I wonder if throwing exception there is the only solution. Maybe another connection type i.e. Unknown can be defined and acted upon accordingly.

**Comment by michellyna** [comment]
Hi behzad62, just to feed my curiosity, is NCP Vpn one of the VPN app you are referring to? We ran into exactly this problem and like you just pointed out, we replaced the exception thrown by "return ConnectionType.Other;". The reason for my question was because you put "apps" so I wonder if there might have other VPN apps using 53 as a interface type value.

**Comment by behzad62** [comment]
Hi michellyna,  
No, the culprit in my case was SoftEther vpn client. It seems as I guessed there are multiple VPN apps using 53 as a interface type value.

> Hi behzad62, just to feed my curiosity, is NCP Vpn one of the VPN app you are referring to? We ran into exactly this problem and like you just pointed out, we replaced the exception thrown by "return ConnectionType.Other;". The reason for my question was because you put "apps" so I wonder if there might have other VPN apps using 53 as a interface type value.

**Comment by michellyna** [comment]
Thank you behzad62 for that information, this confirm that in our case, it's better fixing the code then asking the VPN vendor from changing to a "valid" code. Although 53 is not a valid id from MSDN's doc, it might be an undocumented and accepted value for VPNs.
