### ISSUE TITLE
Xamarin.froms android version 4.4 crash app on CrossConnectivity.Current.IsConnected

### ISSUE THREAD

**Issue by swetanandha** [jamesmontemagno/ConnectivityPlugin#167]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 
Device Tested On: Android 4.4
Simulator Tested On: ---
Version of VS:  ---
Version of Xamarin: 3.2
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
Just tested and works fine. You would need to provide stack trace or logcat.
