### ISSUE TITLE
[WPF] ConnectivityImplementation->ToConnectionTypes -> ArgumentOutOfRangeException for ConnectionType = 53 (IF_TYPE_PROP_VIRTUAL)

### ISSUE THREAD

**Issue by RwSgxx** [jamesmontemagno/ConnectivityPlugin#174]
@jamesmontemagno 
I know that we should use Xamarin.Essentials, but we are working with Xamarin Forms on WPF, and Xamarin.Essentials is not supported on WPF.

## Bug Information

Version Number of Plugin: 3.2.0
Device Tested On: PC 
Simulator Tested On: - 
Version of VS:  16.6.2
Version of Xamarin: 4.6.0.847
Versions of other things you are using:

### Steps to reproduce the Behavior
Install NordVPN (probably most VPNs) -> it will create a network interface of type 53 (IF_TYPE_PROP_VIRTUAL).
Use the plugin in a .Net framework application (WPF) 

### Expected Behavior
It should just say that the ConnectionType = ConnectionType.Other instead of the ArgumentOutOfRangeException .
This interface type 53 (IF_TYPE_PROP_VIRTUAL) is not mapped in .Net, but it exists in windows:
[ipifcons.h](https://github.com/tpn/winsdk-10/blob/master/Include/10.0.14393.0/shared/ipifcons.h)

### Actual Behavior
This network interface type will result in an ArgumentOutOfRangeException  in 
src\Connectivity.Plugin.Net45\ConnectivityImplementation.cs -> ConnectivityImplementation -> ToConnectionTypes

### Screenshots

Thank you!

**Comment by ghost** [comment]
I have the same problem...

**Comment by bhaynesch** [comment]
I have same issue.  Can the ToConnectionTypes method in ConnectivityImplementation.cs be changed to "return ConnectionType.Other" in the default case instead of throwing an Argument out of range exception?

**Comment by JanZeman** [comment]
Hello, I took dependency on this plugin (WPF among others) and as soon as I activate NordVPN my app crashes. It's not simple to catch the exception in a nice manner. 

I understand this plugin is not anymore on the edge of the latest technologies but I would like to use it. I would volunteer doing the Fix PR but will you please create a new NuGet release based on that @jamesmontemagno ? I can see the latest non-beta NuGet is some 4 years old so better asking not to invest the time without having the chance to see it going public. Thank you in advance.
