### ISSUE TITLE
When will be v4 be released?

### ISSUE THREAD

**Issue by wegascee** [jamesmontemagno/ConnectivityPlugin#175]
I saw that v. 3.2.0 is newer than v. 4.0.0.190-beta. Will v4 get out of beta some day? When? Or is Xamarin.Essential the only thing we should ever use? Is the feature set the same?

**Comment by jamesmontemagno** [comment]
i recommend just using Xamarin.Essentials as it has basically all of the features and officially supported. I need to setup Ci and such again, been a while since I looked at things.
