### ISSUE TITLE
Works on Android but not iOS debugger/simulator

### ISSUE THREAD

**Issue by zoanthal** [jamesmontemagno/ConnectivityPlugin#18]
Please fill out either the bug or feature request section and remove whatever section you are not using.
## Bug

Version Number of Plugin: 2.2.12
Device Tested On: Samsung Galaxy Note 5
Simulator Tested On: iOS, multiple simulated devices
### Expected Behavior

In iOS debugger:
bool online = await CrossConnectivity.Current.IsRemoteReachable("google.com");

returns true when the simulator is connected to the Internet.  Not tested on physical Apple device.  Android works correctly.
### Actual Behavior

In iOS debugger:
bool online = await CrossConnectivity.Current.IsRemoteReachable("google.com");

returns false when the simulator is connected to Internet.  
### Steps to reproduce the Behavior

bool online = await Plugin.Connectivity.CrossConnectivity.Current.IsRemoteReachable("google.com");
## Feature Request:

Please fill in what you would like

**Comment by jamesmontemagno** [comment]
Haven't been able to reproduce at all on my test cases on xcode 7 and xcode 8.
