### ISSUE TITLE
[Feature Request] Add network strength

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/ConnectivityPlugin#19]
It would be great having the network strength!

**Comment by aphex3k** [comment]
It would also require another `IsSupported` property at least as this is totally not supported on all mobile platforms i imagine...

**Comment by prashantvc** [comment]
@bbougot Could you elaborate on this request? 
It will be nice if you add more details. 
What are you ideas? And, how it should work?

**Comment by prashantvc** [comment]
Because we have not received a reply to our request for more information, I am marking this issue as closed. If you are still encountering this issue on the latest version of the plugin, please don’t hesitate to reopen the ticket with the requested information. Thanks!
