### ISSUE TITLE
Problem to publish App Store - ipv6 rejected

### ISSUE THREAD

**Issue by markobls** [jamesmontemagno/ConnectivityPlugin#21]
Hi James,
I'm trying to publish to app store but it still rejecting my bynaries.

> However, we continue to encounter one or more bugs in your app when reviewed on iPhone running iOS 9.3.5 on Wi-Fi connected to an IPv6 network.

I'm using HttpClient to connect to my Api hosted on azure, the ip is like https://blabla.azurewebsites.net
What can I do to get apple's aprove?

Thanks.

I'm using the last version from plugin

**Comment by jamesmontemagno** [comment]
That doesn't go through any IP related activities. I have also submitted several apps with the plugin (and others) with no issues. 

For validation have you tried to submit with and without the plugin?

**Comment by markobls** [comment]
Yes, I did

I've published without plugin too, and they rejected.
I really dont know what to do now.. Because on my testes it is working, but apple insist to reject =(

![apple_ss](https://cloud.githubusercontent.com/assets/9846536/18017269/0ec486ec-6ba7-11e6-8b6e-c28ce3cde413.png)

**Comment by jamesmontemagno** [comment]
If they rejected it without the plugin, then it must be something else that you are using or coding against.  Not sure I can really help any further.

**Comment by trevoriancox** [comment]
This plugin has 5 year old code with hardcoded use of IPv4, has it been tested for IPv6?

https://github.com/jamesmontemagno/ConnectivityPlugin/blob/master/src/Connectivity.Plugin.iOS/Reachability.cs

**Comment by jamesmontemagno** [comment]
These are actually just fine as they are white listed from Apple since they are internal loop back.

Has been tested for several months against IPv6.

**Comment by markobls** [comment]
My problem can be solved on azure?
Or it is a Xamarin problem?

**Comment by jamesmontemagno** [comment]
It has nothing to do with Azure or this Plugin from your testing in this case you can specify that URL just fine, it is just hardcoded IPs or something maybe using sockets and such. Without seeing your code or nugets you are using I can't be sure what is going on inside of your app.

**Comment by markobls** [comment]
Im not the only one having this issue :(
I openned a thread on xamarin forum
https://forums.xamarin.com/discussion/comment/217903

On my tests I have no problem to acess my Api, but apple still rejecting :(

Im getting crazy to found a solution :S
hehe

**Comment by trevoriancox** [comment]
@jamesmontemagno I was using an old version of this code but I resubmitted and was rejected again. Not using any sockets or hardcoded IP's in my code. I will remove use of the plugin and try again. Maybe it is a modernhttpclient issue or a bad test on Apple's end - lots of Xamarin users having similar experience.

**Comment by jamesmontemagno** [comment]
@markobls seems like there are a lot of different things in there. Every app could be a bit different based on which HTTPClient handler you are using, if you are using modernhttpclient, or something else.

It sounds like apple rejected your app without the Plugin too, which to me can confirm that it is not the plugin at all.

Did you try to test your app on an IPv6 only network? https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16

**Comment by jamesmontemagno** [comment]
@trevoriancox I have changes in the source code to handle IPv6 changes in the latest plugin releases. It isn't with the hardcoded IPs it is more with socket code that is in the plugin.

I have done the Apple steps to ensure things are working on IPv6 with the plugin, it could be something else though that is causing the issue, which is my suspicion.

**Comment by trevoriancox** [comment]
@jamesmontemagno Good to know, thanks! I agree the problem is likely elsewhere, I hope it is not modernhttpclient!

**Comment by markobls** [comment]
@jamesmontemagno Yes bro, I did and is working without issues :(

**Comment by jamesmontemagno** [comment]
@markobls I really have no other ideas since it isn't the plugin. Could just be apple's weird testing. Have you submitted with additional tracking logic that can report back to you failures in that situation with hockeyapp or something else?
