### ISSUE TITLE
IPv6 app store rejection

### ISSUE THREAD

**Issue by dhaligas** [jamesmontemagno/ConnectivityPlugin#24]
## Bug

We are getting app store rejections saying our app isn't IPv6 compatible.    I see in the reachability sample on xamarin that they are using this line 

adHocWiFiNetworkReachability = new NetworkReachability (ipAddress.MapToIPv6 ());

https://github.com/xamarin/ios-samples/blob/228de75dabe7071b1e56a66856e616e61944e368/ReachabilitySample/reachability.cs#L67

and 

https://github.com/xamarin/ios-samples/blob/228de75dabe7071b1e56a66856e616e61944e368/ReachabilitySample/reachability.cs#L81

Which this plugin doesn't.  Could this be causing the issues?

Version Number of Plugin: 2.2.12
Device Tested On: iPhone 6s
Simulator Tested On: iPhone 6s

**Comment by jamesmontemagno** [comment]
This is not actually the case as the two IPs that I am using are white listed. I have submitted a few app updates already. Many people are getting this false positive for other reasons, and usually another submission they push it through.
