### ISSUE TITLE
IsConnected is always false on iOS 10 when connected to a private Wi-Fi

### ISSUE THREAD

**Issue by cprice70** [jamesmontemagno/ConnectivityPlugin#25]
On iOS 9 or older, IsConnected would return true when connected to a private Wi-Fi (no Internet) however with iOS 10 (gm seed) the value is always false.  It appears the problem is when 
if (!adHocWiFiNetworkReachability.TryGetFlags(out flags)) is called.  No flags are set yet on iOS 9, this same call flags are set.

Are there any changes in iOS 10 for Wi-Fi permission?

**Comment by jamesmontemagno** [comment]
Then changed this in the new versions: https://developer.apple.com/library/content/samplecode/Reachability/Listings/ReadMe_md.html#//apple_ref/doc/uid/DTS40007324-ReadMe_md-DontLinkElementID_11

I have removed, so you should be good to go now :)
