### ISSUE TITLE
Support for .NETStandard?

### ISSUE THREAD

**Issue by FroggieFrog** [jamesmontemagno/ConnectivityPlugin#27]
Ist it possible to support .NetStandard? It is written everywhere to use .NetStandard instead of PCLs, but this plugin is not compatible (yet).

Package Manager console:
Package Xam.Plugin.Connectivity 2.2.12 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Xam.Plugin.Connectivity 2.2.12 supports:
- monoandroid10 (MonoAndroid,Version=v1.0)
- monotouch10 (MonoTouch,Version=v1.0)
- net45 (.NETFramework,Version=v4.5)
- portable-monoandroid10+monotouch10+net45+uap10+win8+wp8+wp81+wpa81+xamarinios10+xamarinmac20 (.NETPortable,Version=v0.0,Profile=net45+wp80+wp81+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10+Xamarin.Mac20+UAP10)
- uap10 (UAP,Version=v1.0)
- win8 (Windows,Version=v8.0)
- wp8 (WindowsPhone,Version=v8.0)
- wp81 (WindowsPhone,Version=v8.1)
- wpa81 (WindowsPhoneApp,Version=v8.1)
- xamarinios10 (Xamarin.iOS,Version=v1.0)

See: [https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) (section: As a library author, what should I do now?)

**Comment by jamesmontemagno** [comment]
Will add support in the future for .NET standard, but for now you can add imports.
