### ISSUE TITLE
Where can I find the source code of version 2.1.2

### ISSUE THREAD

**Issue by sgustafsson** [jamesmontemagno/ConnectivityPlugin#35]
Hi, where can I get the source code of version 2.1.2 ?
https://www.nuget.org/packages/Xam.Plugin.Connectivity/2.1.2

This repo only hosts the 2.2.12 release.

**Comment by jamesmontemagno** [comment]
You would have to go through the commits. My branches are newer concept for me.

Something like: https://github.com/jamesmontemagno/ConnectivityPlugin/commit/5a033fa241e16be80690c03094a1ccecf7f73ebc
