### ISSUE TITLE
ConnectivityTypeChanged not available on 2.2.12

### ISSUE THREAD

**Issue by joanlopez** [jamesmontemagno/ConnectivityPlugin#36]
## Bug (incorrect usage?)

Version Number of Plugin: 2.2.12 (NuGet)
Device Tested On: Windows10 & Android

### Expected Behavior

I want to use the mentioned event as below:
```CrossConnectivity.Current.ConnectivityTypeChanged += OnConnectivityTypeChanged;```

### Actual Behavior

I can't use it! 
The ```ConnectivityChanged``` is working, but the other is not. 
The IDE says that ```Current``` does not have this event.

I've checked that this feature is implemented in the tag ```2.2.12``` so I think it should be available but i'm not sure.

Thanks!

**Comment by jamesmontemagno** [comment]
It is probably in the beta build.

**Comment by joanlopez** [comment]
So, how I can use it?

Thanks!

**Comment by jamesmontemagno** [comment]
Update all the nugets to latest pre-release: https://github.com/jamesmontemagno/ConnectivityPlugin/blob/master/tests/app/ConnectivityTest/ConnectivityTestPage.xaml.cs#L27-L62

**Comment by jamesmontemagno** [comment]
https://www.nuget.org/packages/Xam.Plugin.Connectivity/2.3.0.37-beta
