### ISSUE TITLE
Method 'IsReachable' not found in type 'Plugin.Connectivity.Abstractions.IConnectivity'.

### ISSUE THREAD

**Issue by fasterinnerlooper** [jamesmontemagno/ConnectivityPlugin#38]
## Bug 
When running a Xamarin.Forms app on Android, the IsReachable method cannot be found.
Attempting the following scenario with IsRemoteReachable yields the same results.

Version Number of Plugin: 2.2.12 & 2.3.0.37-beta
Device Tested On: None
Simulator Tested On: KitKat (API Level 19, OS 4.4) on Windows

### Expected Behaviour
IsReachable returns true or false depending on if the host can be accessed

### Actual Behaviour
The code executing IsReachable is skipped. Accessing CrossConnectivity.Current.IsReachable() from the Immediate Window in Visual Studio gives the error message reported in the title.

### Steps to reproduce the Behaviour
Create a new Xamarin.Forms app, set the API level to 19 and implement the IsReachable() method.

**Comment by fasterinnerlooper** [comment]
I should also point out that I had previously implemented a Xamarin.Forms Portable solution with Windows 10 and iOS as the only components, later adding Android. This issue didn't previously affect the solution, and is only a problem on Android though I have not re-tested on the other platforms as of yet.

**Comment by jamesmontemagno** [comment]
Did you install the Nuget into all projects?

**Comment by fasterinnerlooper** [comment]
Here's how things look to me:
![image](https://cloud.githubusercontent.com/assets/1066864/20653302/ecb84154-b4c8-11e6-8059-a2c17c50d192.png)

**Comment by jamesmontemagno** [comment]
Perhaps try to uninstall and re-install or clean and re-build. Would be a NuGet issue, not anything with the Library itself.
