### ISSUE TITLE
IsRemoteReachable() does not work if a proxy is set.

### ISSUE THREAD

**Issue by jeremycookhp** [jamesmontemagno/ConnectivityPlugin#39]
For both Android and iOS, if the WIFI connection is configured using a proxy, the IsReachable() and IsRemoteReachable() calls always return false.   UWP seemed to work ok.

Version Number of Plugin: 2.2.12
Device Tested On:  iPhone 6 plus, iOS 9.3.   Android: multiple versions (4.3, 5.0, 6.0)
Simulator Tested On:

### Expected Behavior
Had hoped that the IsReachable() and IsRemoteReachable() would take into account any system proxy setting, and use that for establishing a connection to determine connectivity.   Since our application will be used often with corporate users that have WIFI connections that need a proxy, we can't reliably use this plug-in to determine connectivity up front.

### Actual Behavior
Calls to IsReachable() and IsRemoteReachable() will timeout and return false.

### Steps to reproduce the Behavior
On an iOS or Android device, configure a connection that uses a proxy to the network.   Verify that the proxy works by checking normal browser connectivity.  Then attempt to use the Connectivity plugin.

## Feature Request:
Am guessing that since no-one else has reported this, maybe no-one else cares about proxy environments.   Would sure be nice to have this supported.   

Thanks
Jeremy

**Comment by jamesmontemagno** [comment]
How does one setup a proxy? Never done it on iOS/Android before. Is there a public one that I can reproduce with?

**Comment by jeremycookhp** [comment]
I think you could test this by setting up iOS / Android WIFI connections to use a bogus manual proxy.   Setting up a manual proxy is just a matter of editing your WIFI connection and adding a manual proxy.   Point it at any address/port.    Test proxy settings by then trying to use a web-browser to reach a valid site.  It should time out and fail.    Now try testing the IsRemoteReachable() calls on a valid server.  If they succeed, you know that it's not correctly using the proxy settings.

Since the proxy is specific to HTTP/HTTPS traffic, I think that the implementation of IsRemoteReachable() would need to use some form of an HTTP/HTTPS call to verify true reachability.

**Comment by jamesmontemagno** [comment]
In this instance I am just marking as won't fix as it is an edge case and I recommend a custom solution for this.
