### ISSUE TITLE
ConnectivityChanged isn't fired when changing from cellular to WiFi

### ISSUE THREAD

**Issue by pasha-o** [jamesmontemagno/ConnectivityPlugin#40]
## Bug 
A bug exists whnever you enable WIFI over Cellular and ConnectivityChanged  never fires/
you can download the solution i attached and test it on android 

Version Number of Plugin: Latest Version 2.2.12
Device Tested On: Samsung Galaxy S7 Edge
Simulator Tested On:

### Expected Behavior
 ConnectivityChanged event should be fired whenever connectivity changes

### Actual Behavior
ConnectivityChanged event only fires from no connectivity to when connectivity is available however it never fires when connectivity changes from cellular to WiFi

### Steps to reproduce the Behavior
1- run the solution attached 
2- enable cellular
3- enable wifi 

## Feature Request:
ConnectivityChanged event needs to raise whenever there is a change in connectivity from any type to any type

**Comment by jamesmontemagno** [comment]
This makes sense. Android doesn't loose connectivity so it reports connected.

You would want to subscribe to: ConnectionTypeChanged

This will tell you when it changes.

**Comment by pasha-o** [comment]
hi James , 

thanks for responding, i am not seeing ConnectionTypeChanged event, only ConnectivityChanged. is this something i need to implement on my own?

thanks
p

**Comment by jamesmontemagno** [comment]
It is available in the pre-release nuget

**Comment by pasha-o** [comment]
hi James, 
I tested the pre-release version 2.3.0.37-beta and i see the event. it works however the event args always return "Cellular" as an active connectivity type doesn't matter if sim card exists or not.

i tested with sim card in and wifi on , I get cellular, cellular, wifi and without simcard i get cellular, wifi 

i also never get bluetooth as a connection type returned when it's active.

also when i turn off wifi and turn it back on i get an exception 
12-02 13:50:34.769 I/MonoDroid(  342): System.NullReferenceException: Object reference not set to an instance of an object.
12-02 13:50:34.769 I/MonoDroid(  342):   at Plugin.Connectivity.ConnectivityImplementation+<GetConnectionTypes>d__14.MoveNext () [0x00060] in C:\projects\connectivityplugin\src\Connectivity.Plugin.Android\ConnectivityImplementation.cs:202 


I know this is a pre-release, but thought to share it with you in case you didn't know

do you want me to file it as a bug?

**Comment by jamesmontemagno** [comment]
So:

1. It doesn't know if you have a sim card in or not. So it will return cellular or wifi. Cellular is the default if it can't figure it out.
2. It would only return bluetooth if it actually is streaming data over and  it would return ConnectivityType.Bluetooth. I have no idea really how to even set that up as you can share internet over bluetooth, but not really the opposite.
3.  I can't reproduce the crash, but I will put some null checks in there. I will have a new beta in about 10 minutes.
