### ISSUE TITLE
IsConnected always reports true on iOS 10

### ISSUE THREAD

**Issue by ronpf** [jamesmontemagno/ConnectivityPlugin#41]
## Bug
IsConnected always reports true on iOS 10 device. Android devices appear to be working correctly

##Version Number of Plugin:
2.2.12

##Device Tested On:
iPhone 6

### Expected Behavior
IsConnected should flip when wifi is turned off/on

### Steps to reproduce the Behavior
Insert into AppDelgate.FinishedLaunching() or into the PCL App() ctor:

CrossConnectivity.Current.ConnectivityChanged += (sender, args) =>
{
    Alert("Connectivity Changed", "IsConnected: " + args.IsConnected.ToString());
};

**Comment by jamesmontemagno** [comment]
Please try the latest beta it was fixed there.
