### ISSUE TITLE
[UWP] Virual Connections -> IsConnected Always returns True

### ISSUE THREAD

**Issue by Onjay** [jamesmontemagno/ConnectivityPlugin#42]
CrossConnectivity.Current.IsConnected always returns True on UWP, but works great on Android. Disabling a couple connected VEthernet connections for my phone emulators fixed the problem. Not sure if support can be added for these virtual connections or not.

## Bug 

Version Number of Plugin: 2.2.12 and 2.2.40 Beta
Device Tested On: UWP
Simulator Tested On:

**Comment by jamesmontemagno** [comment]
Was this tested on device? desktop? simulator?

**Comment by Onjay** [comment]
On my work laptop, debugging a uwp desktop app. It has a number of virtual connections, which when disabled returned a false when my ethernet cable was disconnected and wireless was turned off.  But returned true if the virtual connections were enabled and connected, even the uwp app isnt using them, my laptop apparently thinks so. So maybe your plugin needs a way to check and see if a connected virtual network is really connected to the internet or not.

Mark Garcia



On Sat, Dec 10, 2016 at 12:13 PM -0800, "James Montemagno" <notifications@github.com<mailto:notifications@github.com>> wrote:


Was this tested on device? desktop? simulator?

-

**Comment by jamesmontemagno** [comment]
In your UWP app run this code and let me know what this returns:
```
    var profile = NetworkInformation.GetInternetConnectionProfile();
                if (profile != null)
                    var connectionLevel = profile.GetNetworkConnectivityLevel();
```

Most likely the connection level returned is not "None" which is what I check for and is set to "limited" perhaps which means you have some active connection but may or may not have internet connection of some sort.

**Comment by Onjay** [comment]
I’ll have to run it on Monday morning James. I’ll let you know, but I’ll be you’re right.
Thanks,
Mark

**Comment by Onjay** [comment]
James,

I'm really sorry for not getting back to you sooner, I got sidetracked with debugging another application. If I run the below code in the UWP app's App.xaml.cs file and check my connectively in a mainpageviewmodle pcl using (again Ethernet and wifi disconnected):


        public void CheckNetworkConnectionAsync()
        {
            var connectivityStatus = CrossConnectivity.Current.IsConnected;

            Debug.WriteLine($"connectivityStatus: {connectivityStatus}");

            if (!CrossConnectivity.Current.IsConnected)
            {
                ConnectionMessageIsVisible = true;
            }
            else
            {
                ConnectionMessageIsVisible = false;
            }
        }


I get the following result:

LocalAccess
connectivityStatus: True


I'm sure that disabling all of my virtual connections will result in a False return.



________________________________

**Comment by jamesmontemagno** [comment]
What happens when you run:

```
 var profile = NetworkInformation.GetInternetConnectionProfile();

 if (profile != null)
   var connectionLevel = profile.GetNetworkConnectivityLevel();
```

**Comment by jamesmontemagno** [comment]
Also, try this code:

```
                foreach(var p in NetworkInformation.GetConnectionProfiles())
                {
                    Debug.WriteLine(p.ProfileName + ": " + p.GetNetworkConnectivityLevel());
                }
```

**Comment by Onjay** [comment]
Disconted:

Bluetooth Network Connection: None
Ethernet: None
xfinitywifi: None
AsterHome: None
Nokia: None
A-MSFTWLAN: None
MSFTCORP: None
connectivityStatus: True


Connected:

Bluetooth Network Connection: None
Ethernet: LocalAccess
xfinitywifi: None
AsterHome: None
Nokia: None
A-MSFTWLAN: None
MSFTCORP: None
connectivityStatus: True



________________________________

**Comment by jamesmontemagno** [comment]
For disconnected can you run this:
```
var profile = NetworkInformation.GetInternetConnectionProfile();
Debug.WriteLine(profile.ProfileName + ": " + profile.GetNetworkConnectivityLevel());
```

This will tell us what is returning true basically when you are disconnected.

Thanks for running these :)

**Comment by CDrosos** [comment]
I have the same problem too but on Xamarin.Android, in the latest stable update i get always true, build on android 7, running on android 5 on samsung s3 neo
if i can help please tell me what to do
thanks for your plugins

**Comment by jamesmontemagno** [comment]
@CDrosos you should open a different bug as clearly something specific to UWP and virtual connections is probably different then what you have... are you using Virtual connections on Android??

**Comment by jamesmontemagno** [comment]
Also, @CDrosos  i just tested the latest package and it is working flawless.

**Comment by CDrosos** [comment]
Sorry no i dont use vpn, i just open a new issue

**Comment by keozx** [comment]
Hi @jamesmontemagno bumping on this issue because I believe when there are virtual switches we will get LocalAccess instead of None for the internet connection profile even when unpluged, I think in your code you are just checking for None right? I believe since we want Internet connectivity this should be changed to InternetAccess check? or maybe we can have two properties like IsLocalConnected and IsInternetConnected :)

**Comment by jamesmontemagno** [comment]
@keozx for UWP? are you able to debug through the code and tell me what is being returned up top

**Comment by KarolStosik** [comment]
@jamesmontemagno 

I executed the code you asked for, the result is:
**vEthernet (Internal Ethernet Port Windows Phone Emulator Internal Switch): LocalAccess**

**Comment by KarolStosik** [comment]
Looks like this line is incorrect:

isConnected = profile.GetNetworkConnectivityLevel() != NetworkConnectivityLevel.None;

Can anyone fix it to all && != NetworkConnectivityLevel.LocalAccess ?

**Comment by Koseng** [comment]
IsConnected always returns true (UWP) if there is an activated network interface on windows, no matter if there really is an internet connection. For example on a laptop connected to the internet by WIFI disable WIFI -> IsConnected still returns true but there is no connection. It returns true, due to existing LAN interface (without attached cable).

As stated in the post before this is **wrong**:
`isConnected = profile.GetNetworkConnectivityLevel() != NetworkConnectivityLevel.None;`

**NetworkConnectivityLevel.LocalAccess is missing**, it also has no internet access.
https://docs.microsoft.com/en-us/uwp/api/windows.networking.connectivity.networkconnectivitylevel

Change to something like that:
```
isConnected = (profile.GetNetworkConnectivityLevel() != NetworkConnectivityLevel.None) &&
(profile.GetNetworkConnectivityLevel() != NetworkConnectivityLevel.LocalAccess);
```

**Comment by subbarao493** [comment]
Hi @jamesmontemagno i am facing small problem as follows in UWP
1.Create the hot spot in mobile and switch off mobile data
2.Connected to hot spot using laptop
3.Called "**profile.GetNetworkConnectivityLevel()**" is giving the "**NetworkConnectivityLevel.InternetAccess**" and "**isconnected**" always true
but it does not have any internet Connection can you suggest me how can i solve this problem.
