### ISSUE TITLE
Possible bug with Dual SIM devices

### ISSUE THREAD

**Issue by jjwhite** [jamesmontemagno/ConnectivityPlugin#43]
## Bug 
I am unable to reproduce this issue because I do not have a dual SIM device but we have been getting reports from customers running Android that they are getting No Connection messages on dual SIM devices.  Has this plugin been tested with multiple SIM devices or are there any known issues with these devices?

**Comment by jjwhite** [comment]
I took a look at the source code and there may be an issue in the Android connectivity check.  If the SIM that is being used is not the default network connection then GetActiveNetwork may not be returning the correct network.  Here's a stackoverflow post that might be helpful.  

http://stackoverflow.com/questions/14957617/dual-sim-check-internet-connection-issue

**Comment by jamesmontemagno** [comment]
Good catch :) crazy dual sim devices
I am updating the code to be:

```
 if ((int)Android.OS.Build.VERSION.SdkInt >= 21)
                    {
                        foreach (var network in manager.GetAllNetworks())
                        {
                            var info = manager.GetNetworkInfo(network);

                            if (info?.IsConnected ?? false)
                                return true;
                        }
                    }
                    else
                    {
                        foreach (var info in manager.GetAllNetworkInfo())
                        {
                            if (info?.IsConnected ?? false)
                                return true;
                        }
                    }

                    return false;
```

**Comment by jamesmontemagno** [comment]
Check out 2.3.0.41-beta

**Comment by jjwhite** [comment]
Thanks!

**Comment by jjwhite** [comment]
Just curious if there is a timetable for this update making it to the Xamarin Component?  We're using the component and I'd like to be able to just update that to get this fix.  Thanks again!

**Comment by jamesmontemagno** [comment]
It is just the nuget. I highly suggest not using the component and stick just to the nuget as that is what the component wraps actually :)
