### ISSUE TITLE
On iOS - CrossConnectivity.Current.ConnectivityChanged eventarg => always return True for "IsConnected"

### ISSUE THREAD

**Issue by ravikanasagra1** [jamesmontemagno/ConnectivityPlugin#44]
I am using this connectivity plugin to check Internet connectivity for Xamarin Forms. I was tested connectivity change event using my iPad [iOS9] and it is always return true for IsConnected when I do on or off WIFI from Device.

I am reporting it as Bug.

Version Number of Plugin: 2.2.12
Device Tested On: iPad - IOS 9.3
Simulator Tested On: NIL

Code Snippet - I have added this code in constructor of 
```
CrossConnectivity.Current.ConnectivityChanged += (sender, args) =>
                {
                    DisplayAlert("Connectivity Changed", "IsConnected: " + args.IsConnected.ToString(), "OK");
                };
```

### Actual Behavior
I am using this connectivity plugin to check Internet connectivity for Xamarin Forms. I was tested connectivity change event using my iPad [iOS9] and it is always return true for IsConnected when I do on or off WIFI from Device.

### Expected Behavior
I should get correct status from flag "IsConnected" when I do on or off my WiFi.

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/41

Was fixed in latest beta

**Comment by ravikanasagra1** [comment]
Thank you. Kindly suggest when could I get this fix as part of Nuget Package release so that I can add it into my project.

**Comment by jamesmontemagno** [comment]
You can already add it by checking the pre-release check box :)

**Comment by mikescott8** [comment]
@jamesmontemagno is this fixed in stable NuGet yet? We are using 2.3.0 and running into this it APPEARS (I need to do more testing to know for sure). Should we try  the latest pre-release NuGet package? But wanted to see if I should just try pre-release first.

**Comment by jamesmontemagno** [comment]
I believe this was fixed in 2.3.0, you can try the pre-release though, but i had validated it already.

**Comment by mikescott8** [comment]
Quick test with just upgrading from 2.3.0 to latest pre-release seemed to fix it.

Just FYI.

Mike Hamilton
@mikescott8

________________________________

**Comment by mikescott8** [comment]
seems it is iphone vs ipad issue. doing testing as I speak(type), but the testing I did that lead to my previous post was on a test iphone device we have. The teester of the story did more testing and on iPad it doesn't seem to work correctly there. 

will post my results once I find out more.

**Comment by mikescott8** [comment]
so on the iPad the event for ConnectivityChanged is occurring but the IsConnected is always set to true when passed into the event handler.

**Comment by jamesmontemagno** [comment]
Open a new bug and add sample code so I can test.

**Comment by mikescott8** [comment]
done. I hope I provided enough info in it. if not let me know on the new one

#58
