### ISSUE TITLE
[Feature request] List of avalible WiFi, BT

### ISSUE THREAD

**Issue by jsndk** [jamesmontemagno/ConnectivityPlugin#45]
## Feature Request:
Get a list of WiFi AP's available. (including MAC, NAME, SSID, BSSID, strength etc. what is available)
Get a list of BT devices available. (including MAC, NAME, Id's etc. what is available)

To be used for location, eg. are you Home/Office etc. What room you in and more.

**Comment by michelmoorlag** [comment]
I need to determine if a user is using his home wifi connection so the ssid of the current wifi connection would be very welcome.

**Comment by bluekuen** [comment]
I also would like to get the IP Adress of the currently connected WiFi.
