### ISSUE TITLE
IsConnected returns always true when we use vpn

### ISSUE THREAD

**Issue by CDrosos** [jamesmontemagno/ConnectivityPlugin#46]
## Bug 
I have notice that in the latest version i always get true, even without sim card and wifi off, even on airplane mode. If i disable the vpn it works as expected. This was not happening on the previous version. Im using the app block this! That stop ads though vpn. 

Version Number of Plugin: latest stable
Device Tested On: Samsung galasy s3 neo

### Steps to reproduce the Behavior
Use a vpn and check what IsConnected returns

**Comment by MarcBruins** [comment]
He CDrosos, in which version did it work and on which version it stopped working? We are experiencing this issue as well and i would like to know the exact version to see what has been changed.

**Comment by CDrosos** [comment]
Hello, i dont remember unfortinately the version but i remember i post this thread after i have just update the Connectivity plugin. so the version that released mid january might have create the problem

**Comment by ghost** [comment]
Hi,

I facing issue of IsConnected return always true (no matter the network is on or not) and the event of CrossConnectivity.Current.ConnectivityChanged not able to trigger when network change. This issue only happened on version 2.3.0 and 3.0.1. It is okay for version 2.2.12 and below.

Any one can assist on this issue?

Thank you

**Comment by jamesmontemagno** [comment]
@keafea do you have a vpn network configured?

**Comment by ghost** [comment]
I do not have VPN network in my phone

**Comment by prashantvc** [comment]
What VPN (app/provide) are you guys using? I am not able to reproduce this on Galaxy S7E with MS VPN, and tunnel bear

**Comment by c-lamont** [comment]
Freedome

https://www.f-secure.com/en/web/home_global/freedome

**Comment by CDrosos** [comment]
i was using this: https://hide.me/en/software/android

**Comment by mofadevs** [comment]
@jamesmontemagno We are experiencing the same issue. IsConnected() always returns true when we use VPN on the device. Our app is using Mobileiron VPN Tunnel when running. The configurations are correct and everything else works just fine except IsConnected().
We are using version 2.2.2. Please advise.
