### ISSUE TITLE
2.3.0 missing release notes

### ISSUE THREAD

**Issue by CliffCawley** [jamesmontemagno/ConnectivityPlugin#47]
Version Number of Plugin: 2.3.0

The github releases page doesn't have this release but it's available on https://www.nuget.org/packages/Xam.Plugin.Connectivity/2.3.0

Any chance you can add the release or update the notes on nuget?

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/ConnectivityPlugin/blob/master/CHANGELOG.md
