### ISSUE TITLE
On iPad - CrossConnectivity.Current.ConnectivityChanged eventarg => always return True for "IsConnected" when wifi changes

### ISSUE THREAD

**Issue by mikescott8** [jamesmontemagno/ConnectivityPlugin#58]
## Bug 
On iPad - CrossConnectivity.Current.ConnectivityChanged eventarg => always return True for "IsConnected"

testing for a story where the app sees connection being dropped and restored and displays indicator in application. we are using this plugin. on iOS running on iPhone and on Android devices it seems to work great. But when being tested on an iPad device that has no sim (cell data not set up) and connected by wifi.

If we pull up control panel and turn ON airplane mode it works.
If we pull up control panel and turn OFF wifi status it does call the ConnectivityChanged event handler set up but the IsConnected value is true even when we turned off the wifi.

Version Number of Plugin: 2.3.1.55-beta
Device Tested On: iPad running 10.2.1

### Expected Behavior
the IsConnected to reflect having connection or not

### Actual Behavior
the IsConnected is true when turning off wifi

### Steps to reproduce the Behavior

- setup ConnectivityChanged event handler
- run app
- swipe up and turn off wifi
- event handler runs and value for IsConnected passed in is true, when expected to be false.

### Code snippets
in App.xaml.cs 
in the App constructor:
`            _connectivity = SimpleIoc.Default.GetInstance<IConnectivity>();
            _connectivity.ConnectivityChanged += _connectivity_ConnectivityChanged;
`

Handler
`
private async void _connectivity_ConnectivityChanged(object sender, ConnectivityChangedEventArgs e)
        {
            if (!e.IsConnected)
            {
...some code when losing connection it never gets called if turning off wifi
...BUT does if turn on airplane mode
            }
         }
`

### additional info
if I do the following:
`
                var types = _connectivity.ConnectionTypes;
` 
in the event handler, there is one value returned in types and it is a  "Plugin.Connectivity.Abstractions.ConnectionType.Cellular"

so the plugin seems to see a Cellular connection even though it is not setup on the iPad and no sim (that I know of in it-client device) so can't turn it "off"

**Comment by mikescott8** [comment]
I am thinking you may be able to ignore this issue.

doing a little more digging it seems there might be a sim card in it. I am working with the client tech team to see.

I lean towards this as the iPhone device we have to test with says "No SIM" in settings under Cellular option, but the iPad says "Set Up Cellular Data". I dont have a SIM tool to open the SIM slot, and trying to check with client's device support team.

**Comment by jamesmontemagno** [comment]
ahhhh yes, have you tried airplane mode?

**Comment by mikescott8** [comment]
yes, i mentioned in bug, when turning airplane mode on, it does return false.

so I think this may NOT be a real bug. Sorry for not testing thoroughly enough before reporting. 

when I do  a call to IsRemoteReachable it returns false, even though _connectivity.IsConnected is true.

**Comment by jamesmontemagno** [comment]
yeah, most likely the device still thinks there is connectivity somehow with it. I don't make requests out as it would take time and doesn't return instantly. I think this is kind of as expected.
