### ISSUE TITLE
Android: ConnectionTypes doesn't contain all connections

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/ConnectivityPlugin#6]
Moved from: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/282
## Bug

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
### Expected Behavior

When cellular connection is active AND wifi connection too, ConnectionTypes should contains the 2 types.
By default Android use wifi connection if the 2 are active so I don't really know if it's possible for you to know that but if you could it would be great !
### Actual Behavior

Only Wifi is present in ConnectionTypes
### Steps to reproduce the Behavior

Activate cellular and wifi connection on a device.

**Comment by ghost** [comment]
We updated to 2.2.2. for IPv6 support, but are now experiencing problems with retrieving ConnectionTypes. While the device is connected to WiFi, ConnectionTypes only returns "Other". Reverting to 2.1.2 did solve this issue.

**Comment by bartdkmediahuis** [comment]
Is this something that will be "hotfixed", or are you planning to leave this bug as is and fix it when implementing https://github.com/jamesmontemagno/ConnectivityPlugin/issues/9 ?

**Comment by jamesmontemagno** [comment]
Let me investigate this a little bit more and see what is going on. Will try to push a beta today.

**Comment by jamesmontemagno** [comment]
For iOS I have created a new bug here: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/11
