### ISSUE TITLE
CrossConnectivity.Current.IsReachable & CrossConnectivity.Current.IsConnected always return false on Android

### ISSUE THREAD

**Issue by hadi-altinawi** [jamesmontemagno/ConnectivityPlugin#61]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
Well, I don't know if this is a bug or if I don't know how to use it correctly!
I am not using Xamarin.Forms.
I have a PCL solution which contains xamarin.android solution inside it.
I have installed Xam.Plugin.Connectivity using Nuget only in my PCL.
In my PCL class, I am using:
public static async Task<bool> IsAPIReachable()
        {
            try
            {
                return  await CrossConnectivity.Current.IsReachable("www.google.com");
            }
            catch
            {
                return false;
            }
        }

And in my Android I am calling this method:
if (await MYPCL.PCLClass.IsAPIReachable())
{
  //Show YES
}
else
{
 //Show NO
}

I am always getting NO

I have tried also CrossConnectivity.Current.IsRemoteReachable("google.com") and I am getting false.
And when I tried CrossConnectivity.Current.IsConnected also I am getting false.

Version Number of Plugin: 2.3.0
Device Tested On: Sony Xperia Z3
Simulator Tested On: all visual studio simulators

### Expected Behavior
Return true because I can access internet on my Android device
### Actual Behavior
Return false value
## Feature Request:
Please fill in what you would like
Getting true value

**Comment by jamesmontemagno** [comment]
If you are getting IsConnected == false something is wrong with your android device or emulator.  I can not reproduce and works on all of my devices and emualtors.

**Comment by saaabbir** [comment]
Hi there, i know its a little bit late for this but i use following

```
if (CrossConnectivity.Current.IsConnected == false)
            {
                Debug.WriteLine(CrossConnectivity.Current.IsConnected.ToString());
                GlobalConnectivityIndicator.MyConn.ShowConnectivityIndicator = true;
            }
```
this works fine upto android api 23. but its not working in api 24. also it works perfectly on ios 10.3
