### ISSUE TITLE
iOS 10.3 - ConnectivityChanged event only fires once

### ISSUE THREAD

**Issue by codebeaulieu** [jamesmontemagno/ConnectivityPlugin#64]
## Bug 

Using the following code:
```
CrossConnectivity.Current.ConnectivityChanged += (sender, args) =>
{
    DisplayAlert("Connectivity Changed", "IsConnected: " + args.IsConnected.ToString(), "OK");
};
```

When you load the application and disconnect from the internet you get a ConnectivityChanged event. Then, when you reconnect, you get nothing.

Version Number of Plugin: 2.3.0
Device Tested On: iPad Pro
Simulator Tested On: iPhone 7 iOS 10.3

### Expected Behavior
Every time the connection changes the event fires.

### Actual Behavior
The event only fires when you disconnect. Never when you connect.

### Steps to reproduce the Behavior
Install plugin, use above code.

**example project:** 
https://github.com/codebeaulieu/Connectivity/blob/master/FirstStepsReactiveUI/UserInterfaces/Dashboard.cs#L61

**Comment by reynsoto** [comment]
The same was happening for android when I turn on/off the airplane mode using this version. ConnectivityChanged never gets called in this version(2.3.0) but when rolled back to v2.2.12  it works fine.

**Comment by codebeaulieu** [comment]
Good to know. I just might have to do that.

**Comment by codebeaulieu** [comment]
@reynewrey That totally worked. Thanks for the tip

**Comment by reynsoto** [comment]
I'm glad it worked for you @codebeaulieu

**Comment by jamesmontemagno** [comment]
Hmmm this is something else as it worked on 10.2 and 9.3 from my testing just fine. Going to revert my fix.

**Comment by jamesmontemagno** [comment]
I just tested this again and it is working fine actually. It may take a few extra seconds for it trigger in, but seems to work fine. I will continue testing. Perhaps it is newtwork based.

**Comment by prom3theu5** [comment]
I am noticing a similar issue
When on 4G I notice as above, the disconnected event never fires - even when you take the sim card out
However Wifi is 100% working and fires everytime.

**Comment by jamesmontemagno** [comment]
Closing as it really isn't reproducible.
