### ISSUE TITLE
Url With Port Number Returns Not Reachable

### ISSUE THREAD

**Issue by dhewitson** [jamesmontemagno/ConnectivityPlugin#68]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.3.0
Device Tested On: iPhone 7  (iOS 10.3.1)
Simulator Tested On: iPhone 7 SE (iOS 10.3)
Version of VS: VS for MAC (7.0.1 (build 24))
Version of Xamarin: 2.3.3.193
Versions of other things you are using:

### Steps to reproduce the Behavior
Attempt to check if url is reachable when the url contains a port number e.g: localhost:4001

### Expected Behavior
Expected to return "true" result.

### Actual Behavior
Returns false

### Code snippet
Do the following with a URL that has a port number in it (e.g: localhost:43092)
```
         if (!await CrossConnectivity.Current.IsRemoteReachable(urlToReach))
         {
                 if (!await CrossConnectivity.Current.IsReachable(urlToReach))
                     return ConnectionStatus.UrlUnreachable;   
         }

        return ConnectionStatus.Connected;
```

**Comment by jamesmontemagno** [comment]
What happens when you open up safari and try to navigate to your localhost? where is the host even running on your iPhone?

**Comment by dhewitson** [comment]
Safari will open the url. "localhost" is the example, probably a poor example. We have a local iis server with port bindings to applications that are available on our network that we use for testing.

**Comment by dhewitson** [comment]
also worth noting the url is reachable if i use httpclient.

**Comment by jamesmontemagno** [comment]
it probably can't resolve local host. Have you tried the IP address?

**Comment by dhewitson** [comment]
IP address doesn't work either.

If i use "172.1.1.0" it works, but if i use "172.1.1.0:44305" it fails.

**Comment by jamesmontemagno** [comment]
Task<bool> IsRemoteReachable(string host, int port = 80, int msTimeout = 5000);

This takes in a port address to pass in. Have you tried that?

**Comment by dhewitson** [comment]
I hadn't until you mentioned it. I'm still not getting connected. If this is more likely a network related problem I'm happy to go with a workaround that I'm already using and we can close the bug?

**Comment by jamesmontemagno** [comment]
What if you just try this:
```csharp
 try
                {
                    var address = "localhost"; //or try the IP
                    var port = 44305;


                    using (var socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
                    {
                        socket.SendTimeout = 3000;
                        socket.ReceiveTimeout = 3000;
                        await socket.ConnectAsync(address, port);
                        canSee = true;
                        socket.Shutdown(SocketShutdown.Both);
                    }

                }
                catch
                {
                }
```

**Comment by jamesmontemagno** [comment]
So, on a mac, I did the file->new xamarin.forms + asp.net core backend and tried this code:

var conncted = await CrossConnectivity.Current.IsRemoteReachable("localhost", 53924);


And worked great... So not sure. I could try on a device with the machines IP address I guess, but assuming will be similar.

**Comment by dhewitson** [comment]
Our target framework is PCL 4.5 Profile 111, would this have anything to do with it?

**Comment by jamesmontemagno** [comment]
Shouldn't at all as it just calls into the native code. I would try to pull the code from the iOS project and run it and see what yours says to debug more.

**Comment by dhewitson** [comment]
OK, I'll give that a go and get back to you

**Comment by jamesmontemagno** [comment]
Closing as can not reproduce locally.
