### ISSUE TITLE
the 

### ISSUE THREAD

**Issue by StanleyBroo** [jamesmontemagno/ConnectivityPlugin#69]
## Bug Information

Version Number of Plugin: 2.3.0
Device Tested On: XAMARIN PREVIEWER

reproduce: 
1) Start Xamarin PREVIEWER
2) Add this code to any page
3) View in PREVIEWER - CRASH..
        protected override void OnAppearing()
        {
            base.OnAppearing();
            if (CrossConnectivity.Current.IsConnected)
                ConnectionBad_img.IsVisible = false;

mono.android.DesignerException: System.NullReferenceException: Object reference not set to an instance of an object
Caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object  at Plugin.Connectivity.ConnectivityChangeBroadcastReceiver.get_ConnectivityManager () [0x0001f] in

**Comment by jamesmontemagno** [comment]
I assume you mean the form previewer? Who knows though? 

If so that is fixed in 3.0

**Comment by jadenrogers** [comment]
Yes forms previewer. Same issue here.

Fixed in version 3 of what, Forms or the plugin?

**Comment by jamesmontemagno** [comment]
Plugin
