### ISSUE TITLE
Can we know whether cellular network is 2G or 3G or 4G

### ISSUE THREAD

**Issue by avinash-ramireddy** [jamesmontemagno/ConnectivityPlugin#72]
Hi,
I would like to know whether  network  type is 2/3/4 G.

I know there is _ConnectionTypes_ available but it's just telling whether it's cellular or wifi.
I need this to check whether to  load large data or in bits based on the network speed.

Is bandwidth an option for such cases?

**Comment by mikemacdev** [comment]
There is a Bandwidths field, which is probably more useful than knowing the generation number based on your question.
