### ISSUE TITLE
Doesn't install package if targetting .NetStandard 1.4 in a Xamarin Portable project.

### ISSUE THREAD

**Issue by mauricio-bv** [jamesmontemagno/ConnectivityPlugin#74]
I am trying to install this plugin in a Xamarin Project but fails. I am targeting .Net Standard 1.4 for the Portable project. Is it possible to install this plugin in a .Net Standard targeted project?

Restoring packages for E:\.......\project.json...
Package Xam.Plugin.Connectivity 2.3.0 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Xam.Plugin.Connectivity 2.3.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - net45 (.NETFramework,Version=v4.5)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - uap10 (UAP,Version=v1.0)
  - win8 (Windows,Version=v8.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - wp81 (WindowsPhone,Version=v8.1)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
One or more packages are incompatible with .NETStandard,Version=v1.4.
Package restore failed. Rolling back package changes for '.....'.

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.3.0
Device Tested On: Windows 10
Simulator Tested On: Windows 10
Version of VS:  2017
Version of Xamarin: 2017
Versions of other things you are using:

### Steps to reproduce the Behavior
Install this package in a Xamarin portable class that targets .Ne Framework 1.4
### Actual Behavior
Fails installation
### Code snippet
N/A
### Screenshotst
N/a

**Comment by jamesmontemagno** [comment]
See: http://motzcod.es/post/148657853472/installing-a-pcl-into-netstandard-libraries

I am slowly upgrading everything to .net standard libraries.

**Comment by mauricio-bv** [comment]
Great! Thank you

**Comment by mauricio-bv** [comment]
James.
Your post in the link you provided above is incomplete (cut off) in the instructions for VS2017:

**Visual Studio 2017 Update
Now in 2017 you have a new .NET Standard project is way easier… simply edit your .csproj and you will see:**

And nothing shows after that. What would be the fix for VS2017?

**Comment by jamesmontemagno** [comment]
There is a file here: https://gist.github.com/jamesmontemagno/0d457cd717f33d7a21efa2caa12ad4d3#file-gistfile1-txt
