### ISSUE TITLE
ConnectivityChanged event not firing if there is navigation inside the winphone app 

### ISSUE THREAD

**Issue by Duraiamuthan** [jamesmontemagno/ConnectivityPlugin#76]
Version Number of Plugin: 2.3.0
Device Tested On: Microsoft Lumia 640 LTE,Windows 8.1 Update 1
Simulator Tested On:nil
Version of VS: MS Professional 2015
Version of Xamarin:4.5.0.476
Versions of other things you are using:
Windows Phone SDK 8.0

### Bug description
Basically I wanted to run some code when internet connectivity is turned on in xamarin native platforms.This problem is happening only on windows phone not in iOS and Android.

### Steps to reproduce the Behavior
1.Create Xamarin native project with winphone 
2.Have couple of pages
3.Place the code in app.xaml.cs of .winphone project as its in below code snippet
4.Turn the wifi off and turn the wifi on and make some navigation in the same windows phone app  till the internet is completely on 
_ConnectivityChanged_ never gets fired

### Expected Behavior
Even if there is navigation happening within the app the _ConnectivityChanged_ should get fired
(Applicable to windows phone only)

### Actual Behavior
If there is a navigation happening within the app then the _ConnectivityChanged_ never gets called 
if there is no navigation happening within the app then _ConnectivityChanged_ get called

### Code snippet
    
**App.xaml.cs**       

    public App()
       {
       
     CrossConnectivity.Current.ConnectivityChanged += async delegate(object sender, Plugin.Connectivity.Abstractions.ConnectivityChangedEventArgs e)
            {
                if (e.IsConnected)
                {
                 await mymethod1();
                }
            };
       }

### Screenshotst
sorry,its a functional bug so couldn't attach any screenshot

**P.S**
I had a similar problem with Timer basically its do with winphone and there was no problem for iOS and Android

**App.xaml.cs**    
    
     protected override async void OnLaunched(LaunchActivatedEventArgs e) {
     GalaSoft.MvvmLight.Messaging.Messenger.Default.Register<myObj>(this, myObj =>   {        
     System.Threading.Timer timerObj = new System.Threading.Timer(myMethod2,Value,1000, System.Threading.Timeout.Infinite);               
     });
     }

In the above code the timer will not get fired if there is any navigation happening in the windows phone project.Even though the same code works fine in iOS on _didFinishLauncing_ and _OnCreate_ in Android

I fixed the above problem by declaring timer object globally in App.xaml.cs and using the instance down there in OnLaunced then this problem didn't happen again.

     public sealed partial class App : Application
     {
     private System.Threading.Timer timerObj;

     protected override async void OnLaunched(LaunchActivatedEventArgs e) {
     GalaSoft.MvvmLight.Messaging.Messenger.Default.Register<myObj>(this, myObj =>   {        
     timerObj = new System.Threading.Timer(myMethod2,Value,1000, System.Threading.Timeout.Infinite);               
     });
     }
  
**Note:**

I have the **ConnectivityChanged** event handler in PCL its working fine for iOS and Android if there is navigation happening inside the windows phone app then at the time the event is not getting called to simplify this problem I have brought in the example with app.xaml.cs

**Comment by jamesmontemagno** [comment]
I no longer support Windows Phone 8/8.1 and no new bug fixes will be done.

**Comment by Duraiamuthan** [comment]
@jamesmontemagno This bug is happening in Windows 10 too

**Comment by jamesmontemagno** [comment]
In a UWP project? Please open a new issue

**Comment by jamesmontemagno** [comment]
with a sample project

**Comment by Duraiamuthan** [comment]
This one is happening in .winphone project.I am sure it would happen with .uwp too.. the problem is how to use **ConnectivityChanged** in windows project(.winphone,.uwp)

**Comment by jamesmontemagno** [comment]
I just tested on UWP and working great in my sample app in the 3-0-standard branch, so perhaps it is already fixed.

**Comment by Duraiamuthan** [comment]
Thats great 💯

**Comment by Duraiamuthan** [comment]
I had to implement my own network change handler in win phone project and the problem that I was mentioning is reproducible if I run Xamarin.winphone in windows 10 too..I am not sure about UWP and windows 10
