### ISSUE TITLE
System.NotImplementedException on Apple TV

### ISSUE THREAD

**Issue by vandenbrakel** [jamesmontemagno/ConnectivityPlugin#78]
Hi,

While using the plugin in an ATV project we encounter a System.NotImplementedException. On the iOS and Android version this does not happen. Any idea's?

This is the PCL code

```
// check for wifi
			bool isWifiOn = false;
			Show ("Checking wifi");
			foreach (Plugin.Connectivity.Abstractions.ConnectionType item in CrossConnectivity.Current.ConnectionTypes) {
				// do your stuff 
				
				if (item.Equals (Plugin.Connectivity.Abstractions.ConnectionType.WiFi)) {
					isWifiOn = true;
				}
			}
```
Error:
This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.			

## Bug Information

Version Number of Plugin: 2.30
Device Tested On: None
Simulator Tested On: ATV simulator
Version of VS: 7.01.24
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
Execute code on atv simulator

### Expected Behavior
No exception

### Actual Behavior
Exeption as described occurs

**Comment by jamesmontemagno** [comment]
This was added in the pre-release sorry for the documentation error.
