### ISSUE TITLE
UWP Release build fails on version 3.0.1

### ISSUE THREAD

**Issue by ckrempp91** [jamesmontemagno/ConnectivityPlugin#81]
I have encountered an issue building my UWP app in release mode when updating to the latest version of the connectivity NuGet (version 3.0.1). I have attached a screenshot that shows the exception occurring in Visual Studio.

Version Number of Plugin: 3.0.1
Version of VS:  Visual Studio 2015 Update 3
Version of Xamarin: 4.3.784

### Steps to reproduce the Behavior
* Upgrade the NuGet to version 3.0.1
* Ensure configuration is set to "Release"
* Build the UWP project
* During the build, it will fail, and OutOfMemoryException will be thrown

### Expected Behavior
Package is build successfully

### Actual Behavior
Encounter OutOfMemoryException when the .NET Native compiling occurs.

### Screenshots
![vs_error](https://user-images.githubusercontent.com/15944499/27911709-9fd18a94-621f-11e7-891b-7517e11e1334.png)

**Comment by jamesmontemagno** [comment]
I have shipped an app already with 3.0.1 and tested this out using VS 2017. Haven't seen any error. Seems like this is with .NET Native, may want to open an issue there.  I have 15 of my plugins all built the same way in my UWP app, working great.

**Comment by ckrempp91** [comment]
After investigation the issue was because I had MSBuild v.14, which is packaged with Visual Studio 2015. So I installed Visual Studio 2017 and got the new MSBuild v.15 and rebuilt the solution, now everything is building and working correctly. It may be good to add a note to the ReadMe, in case someone else encounters this issue. 

Thank you for your time, and for providing this NuGet!
