### ISSUE TITLE
Android - IsConnected always return true and Event not triggered

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/ConnectivityPlugin#82]
## Bug Information
Version Number of Plugin: 3.0.1 & 2.3.0
Device Tested On: Samsung S7 Edge
Version of VS: VS 2017 Enterprise
Version of Xamarin: 4.5.0.433
Versions of Xamarin Forms: 2.3.4.224

### Steps to reproduce the Behavior
1. Turn on Wifi connection
2. Turn off the connection / change to cellular connection

### Expected Behavior
IsConnected flag return true (when there is network available, Wifi/Cellular).

The event of CrossConnectivity.Current.ConnectivityChanged will able to triggered when network change.

### Actual Behavior
IsConnected flag always return true (no matter the network is on or not). 

The event of CrossConnectivity.Current.ConnectivityChanged not able to trigger when network change. This issue only happened on version 2.3.0 and 3.0.1. It is okay for version 2.2.12 and below.

### Code snippet
        protected override void OnAppearing()
        {
            base.OnAppearing();
            Plugin.Connectivity.CrossConnectivity.Current.ConnectivityChanged += Current_ConnectivityChanged;
            UpdateStatus();
        }

        protected override void OnDisappearing()
        {
            base.OnDisappearing();
            Plugin.Connectivity.CrossConnectivity.Current.ConnectivityChanged -= Current_ConnectivityChanged;
        }

        private void Current_ConnectivityChanged(object sender, Plugin.Connectivity.Abstractions.ConnectivityChangedEventArgs e)
        {
            UpdateStatus();
        }

        private void UpdateStatus()
        {
            Plugin.Connectivity.Abstractions.IConnectivity plugin = Plugin.Connectivity.CrossConnectivity.Current;
            Label_IsConnected.Text = plugin.IsConnected.ToString();

            string connectionTypes = string.Empty;
            foreach (Plugin.Connectivity.Abstractions.ConnectionType ct in plugin.ConnectionTypes)
            {
                if (!string.IsNullOrWhiteSpace(connectionTypes)) connectionTypes += ", ";
                connectionTypes += ct.ToString();
            }
            Label_ConnectionTypes.Text = connectionTypes.ToString();

            string bandwidths = string.Empty;
            foreach (ulong bandwidth in plugin.Bandwidths)
            {
                if (!string.IsNullOrWhiteSpace(bandwidths)) bandwidths += ", ";
                bandwidths += bandwidth.ToString();
            }
            Label_Bandwidths.Text = bandwidths.ToString();
        }

### Screenshotst
**With Version 2.2.12 With WIFI**
![with version 2 2 12 with wifi](https://user-images.githubusercontent.com/8998074/28002410-8babd038-6567-11e7-897d-63c352ae4920.png)
**With Version 2.2.12 Without WIFI**
![with version 2 2 12 without wifi](https://user-images.githubusercontent.com/8998074/28002411-8bb1aa1c-6567-11e7-9700-d4d2cb72a7ff.png)
**With Version 3.0.1 With WIFI**
![with version 3 0 1 with wifi](https://user-images.githubusercontent.com/8998074/28002412-8bb2318a-6567-11e7-9a58-14043e69d4e8.png)
**With Version 3.0.1 Without WIFI**
![with version 3 0 1 without wifi](https://user-images.githubusercontent.com/8998074/28002413-8bc9bb98-6567-11e7-86b9-05a734241f69.png)

**Comment by jamesmontemagno** [comment]
It seems like you have internet the whole time, which is why you don't get a change in connectivity. 

It seems like you may want to do a ConnectivityTypeChanged event to see what network has changed... Does that fire?

We changed how the implementation worked a bit during that time..

```
 //When on API 21+ need to use getAllNetworks, else fall base to GetAllNetworkInfo
                //https://developer.android.com/reference/android/net/ConnectivityManager.html#getAllNetworks()
                if ((int)Android.OS.Build.VERSION.SdkInt >= 21)
                {
                    foreach (var network in manager.GetAllNetworks())
                    {
                        var info = manager.GetNetworkInfo(network);

                        if (info?.IsConnected ?? false)
                            return true;
                    }
                }
                else
                {
                    foreach (var info in manager.GetAllNetworkInfo())
                    {
                        if (info?.IsConnected ?? false)
                            return true;
                    }
                }
```

based on the version of android you are running there is a new api.

We we says is.. If any of the connections have a connection then it is valid.

Perhaps you have some other connection going on which is that "Other".

**Comment by jamesmontemagno** [comment]
In addition basically following the standard implementation:
https://stackoverflow.com/questions/32242384/getallnetworkinfo-is-deprecated-how-to-use-getallnetworks-to-check-network

**Comment by jamesmontemagno** [comment]
What happens if you go into airplane mode?

**Comment by jamesmontemagno** [comment]
Ahh,,

Additionally, we no longer trigger slight network changes like that.

We do this when a change triggers to give the network manager a chance to register the new network.
```
  //await 500ms to ensure that the the connection manager updates
            await Task.Delay(500);
```

This was to fix: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/59

And is the new expected behavior.

I have updated 3.0.2-beta to get rid of some of the "unknown" networks on there.

**Comment by ghost** [comment]
I had added event for ConnectivityTypeChanged. However, the IsConnected still return true even there is no network connection.

I was using Android 7.0 version

**Comment by jamesmontemagno** [comment]
It seems as though one of your connections does have internet connection or it thinks it has internet connection. 

I can see the little cellular signal there.

I have tested on 5.1.1, 4.4, and 7.0 devices and working for me.

My recommendation is to put the code into your actual Android app and see what the issue is. You can pull down the "test" project and just run that and test it easily.

**Comment by ghost** [comment]
I had installed latest version 3.0.2. I still getting **CrossConnectivity.Current.IsConnected** ==> return **true** when no wifi/cellular network/airplane mode.

It was no issue in version 2.2,12. Any other reason can cause this issue?

I had deployed the app to my actual android phone. However the result still same.

**Comment by jamesmontemagno** [comment]
Try the 3.0.3 beta and let me know

**Comment by ghost** [comment]
I had installed 3.03 beta and deployed to following devices:
1. Xiaomi Redmi 3S (Android 6.0 - API 23) --> Working properly in no wifi/cellular network/airplane mode.
2. Samsung S7 Edge (Android 7.0 - API 24) --> Still getting **CrossConnectivity.Current.IsConnected ==> return true** in no wifi/cellular network/airplane mode.

Previously I always deployed to **Samsung S7 Edge (Android 7.0 - API 24)** and having this issue, until today deployed to **Xiaomi Redmi 3S (Android 6.0 - API 23)** then realize this issue was only happened in **Samsung S7 Edge (Android 7.0 - API 24)**. 

Is it latest codes (above **v2.3.0**) not support **Android 7.0 - API 24** ? As I tested (**v2.2.12**) was okay for both devices.

**Comment by jamesmontemagno** [comment]
@keafea most likely it is just the S7 reporting incorrect. See; https://github.com/jamesmontemagno/ConnectivityPlugin/issues/90

API 21+ use the same exact code: https://github.com/jamesmontemagno/ConnectivityPlugin/blob/master/src/Connectivity.Plugin.Android/ConnectivityImplementation.cs#L65

So literally it is your device reporting back the incorrect information. You can run the code that is in there in your Android app and verify for yourself.

This code change was for https://github.com/jamesmontemagno/ConnectivityPlugin/issues/43 for dual sim cards. The old code was: https://github.com/jamesmontemagno/ConnectivityPlugin/blob/release-2.2.12/src/Connectivity.Plugin.Android/ConnectivityImplementation.cs#L66

I recommend you help out by actually following what I recommended and showed in #90 to help diagnose

**Comment by jamesmontemagno** [comment]
Based on #90 I am going to try to filter out dummy subtypes, which I assume is your issue:

Try 3.0.3-beta123

**Comment by ghost** [comment]
Will try your recommended solution later. Thanks for it, ^^
