### ISSUE TITLE
Cross.Connectivity.Current.ConnectivityChanged does not work on IOS Visual Studio emulator

### ISSUE THREAD

**Issue by AlejandroPiCano** [jamesmontemagno/ConnectivityPlugin#85]
Hello,
To test the connectivity of my app testing change from offline to online mode and vice-versa using this plugin, I need to do so first in the emulator. Xamarin Android Player emulator works well, but in the IOS does not, do not detect really when connected to a wifi network or when not is disconnected.
However in the IPhone physical devices if it works well.

## Bug Information

Version Number of Plugin:2.3.0
Device Tested On:
Simulator Tested On:IPhone 6 simulator VS 2017
Version of VS: Visual Studio Enterprise 2017 v.15.2
Version of Xamarin:4.5.0.486
Versions of other things you are using:

### Steps to reproduce the Behavior
1-Run the app with the emulator
2-Put breakpoint in Cross.Connectivity.Current.ConnectivityChanged delegate method
3-Put emulator in airplane mode.

### Expected Behavior
The debug stopping in the breakpoint.

### Actual Behavior
The debug does not stop in the breakpoint, but it does in physical device.

**Comment by Suriman** [comment]
Me too!.

**Comment by jamesmontemagno** [comment]
You would have to turn off the wifi on your mac to get the change.. event. The remote iOS simulator is not supported in this situation, you would have to use the simulator on a macOS device from VS for Mac
