### ISSUE TITLE
iOS - ConnectionTypes always returns Wifi

### ISSUE THREAD

**Issue by duckwaffle** [jamesmontemagno/ConnectivityPlugin#87]
## Bug Information

Version Number of Plugin: 3.0.1/3.0.2-beta106
Device Tested On: iPhone 6 / iOS 10.3.2
Simulator Tested On: n/a
Version of VS: 2017
Version of Xamarin: 10.10.0.37
Versions of other things you are using:

### Steps to reproduce the Behavior
Start debugging with wifi set to "off"

### Expected Behavior
CrossConnectivity.Current.ConnectionTypes returns only Cellular

### Actual Behavior
CrossConnectivity.Current.ConnectionTypes returns Cellular and Wifi

### Code snippet
        public bool IsConnectedToWifi()
        {
            var connetionTypes = CrossConnectivity.Current.ConnectionTypes;
            return connetionTypes.Contains(ConnectionType.WiFi);

It's also worth noting that I ran this test with my device not connected to a mac/debugger, where a UI would prompt if the Wifi value was not found. This prompt only shows when I have the device set to airplane mode.

**Comment by Nickolas-** [comment]
Same here, after update to latest packages , it always return WiFI

**Comment by jamesmontemagno** [comment]
Was able to repro on a device with a sim card in it, doesn't repo if no sim card.

**Comment by Nickolas-** [comment]
Was this pushed to beta-117 ?

**Comment by jamesmontemagno** [comment]
correct in the latest
