### ISSUE TITLE
ConnectionTypes error in Android 4

### ISSUE THREAD

**Issue by ndesorden** [jamesmontemagno/ConnectivityPlugin#88]
Version Number of Plugin: 2.3.0, 3.0.1
Device Tested On: Android jelly bean and kitkat
Simulator Tested On: Genymotion and Android Emulator

In Android 4.x (tested in Jelly Bean and KitKat) ienumerable ConnectionTypes contains wifi with wireless connection enabled **OR** disabled

`string.Join(",", CrossConnectivity.Current.ConnectionTypes) -> Cellular,WiFi,Cellular,Cellular,Cellular,Cellular,Cellular,Cellular,WiFi
`

With Android 5, 6 ConnectionTypes works as expected, without duplicates connection types and only actives

Tested with ConnectivityPlugin version 2.3.0 and 3.0.1

Regards!

**Comment by jamesmontemagno** [comment]
This is fixed in the beta 3.0.2

**Comment by ndesorden** [comment]
Hi James,

with 3.0.2 in android 4.4.2 ConnectionTypes still returns Wifi when wireless is disabled in real devices.
With emulators works ok.

Thanks
