### ISSUE TITLE
Not working in Android Api 24

### ISSUE THREAD

**Issue by saaabbir** [jamesmontemagno/ConnectivityPlugin#90]
## Bug Information

Version Number of Plugin: 3.0.2
Device Tested On: Samsung S8+
Simulator Tested On: Android 6.0 Api 23
Version of VS: 2017
Version of Xamarin: 4.5.0.486
Versions of other things you are using:

### Expected Behavior
On connection change event it should fire up the change event in OnStart() and also when application starts it should check the state of connection
### Actual Behavior
ios is working perfect which is running 10.3. 
android up to api 23 working fine
android 7.1 api 24 is not working. Tested on Samsung Galaxy S8+

### Code snippet
```
protected override void OnStart ()
		{
            // Handle when your app starts

            //Show connectivity alert when app starts if in disconnected state
            if (CrossConnectivity.Current.IsConnected == false)
            {
                GlobalConnectivityIndicator.MyConn.ShowConnectivityIndicator = true;
            }
            //on connectivity state change add change handler
            CrossConnectivity.Current.ConnectivityChanged +=  (sender, args) =>
            {
                if (args.IsConnected==true)
                {
                    //Debug.WriteLine("connected");
                    GlobalConnectivityIndicator.MyConn.ShowConnectivityIndicator = false;
                }
                else
                {
                    //Debug.WriteLine("disconnected");
                    GlobalConnectivityIndicator.MyConn.ShowConnectivityIndicator = true;
                }
                
                //Debug.WriteLine($"Connectivity changed to {args.IsConnected}");
            };
        }
```

**Comment by jamesmontemagno** [comment]
Describe what is working and not... the "IsConnected"? 

Working on my 3 different devices... API 19, 21, 24.

**Comment by saaabbir** [comment]
Hi, 
Sorry for my poor explanation. I just tested again on my S8+. The IsConnected is working fine. Only problem is ConnectivityChanged is not firing.

I just got my hands on another Samsung Galaxy S3 and I just tested in this device. The ConnectivityChanged event is firing as expected.

FYI: I need ConnectivityChanged to fire up in application level since my app is heavily based on web service therefore I am using this inside App.xaml.cs's OnStart() method. 
I am quite new in mobile development so if you need any further information please let me know what sort of information you are expecting. 

Thanks for your prompt response.

**Comment by saaabbir** [comment]
Hey, just discovered an interesting thing. To check the **ConnectivityChanged** event I normally turn on/off aeroplane mode. Out of curiosity I added **ConnectivityTypeChanged** then I turned **Aeroplane Mode On** and on the debug window i found the following output:

> [0:] Connectivity changed to True
> [0:] Connection Type Other
> [0:] Connection Type Cellular

Even though I do not have any internet connection, telephony service and messaging service its saying I have Other and Cellular connection available. Is that the reason why ConnectivityChanged is not firing? Again this is only happening on Samsung S8+ Api 24 Android 7.0

**Comment by jamesmontemagno** [comment]
try the 3.0.3 beta and let me know

**Comment by saaabbir** [comment]
ok i will let you know in an hour.

`NuGet Message: This package has not been indexed yet. It will appear in search results and will be available for install/restore after indexing is completed.`

so still waiting. once i am done i will give you a heads up

**Comment by saaabbir** [comment]
Still the same :(

**Comment by jamesmontemagno** [comment]
Here, this is simple because you phone is report it back incorrect.

Run this code in your Android project:

```
bool IsConnected()
{
foreach (var network in manager.GetAllNetworks())
                    {
                        try
                        {
                            var info = manager.GetNetworkInfo(network);

                            if (info == null || !info.IsAvailable)
                                continue;

                            if (info.IsConnected)
                                return true;
                        }
                        catch
                        {
                            //there is a possibility, but don't worry
                        }
                    }
return false;
}
```


Tell me what hits "return true;" And investigate it and tell me all of the properties that it is set on.

**Comment by saaabbir** [comment]
Hey just ran it. Adding a screenshot though not sure if thats what you wanted to see. let me know. 
![mobile true](https://user-images.githubusercontent.com/26071889/28939516-803b91ae-7889-11e7-9eee-a08d6d56ac17.jpg)

**Comment by jamesmontemagno** [comment]
I mean it is working exactly as expected.... your phone is literally telling me that LTE is active and ther eis a connection...

Do you have a vpn or something configured?

**Comment by jamesmontemagno** [comment]
I am trying something out based on what you have, which is a subtype of dummy... which is strange... so let me try to filter that out..

Try 3.0.3-beta123

**Comment by saaabbir** [comment]
Hey sorry for my late response. I will be out of town until Monday. I will post an update as soon as I am back. Thanks

**Comment by saaabbir** [comment]
Hey its working now even though i havent tested rigorously yet. Once i do that i will give you a heads up again. Thanks for your support. Really appreciate

**Comment by saaabbir** [comment]
Hi James, I just discovered one problem. That is when I am not connected to wifi and I put my phone on aeroplane mode it notifies me that i am disconnected from the internet but while being connected to wifi if i put it on aeroplane mode it doesnt do anything as if its connected to the internet. Just to clarify further when i put it on aeroplane mode my wifi stays turned off/disconnected. This happens only on API 24 (Samsung S8+).
Please have a look.
Thanks

**Comment by jamesmontemagno** [comment]
You need to debug this further on your phone and see what if anything it is saying is connected.

Does it still say you are connected to the internet?

**Comment by saaabbir** [comment]
Hi again,

I have checked debugging info just now.  

Issue: Cellular on and Wifi off - hits "!info.IsAvailable"
Basically when it loops through all available connection methods (wifi/cellular) i can see it gets the right info as in it first checks wifi and return false which is correct. then checks cellular returns true. Here is the debugging info in order of execution:

> info = {[type: WIFI_P2P[] - WIFI_P2P, state: DISCONNECTED/DISCONNECTED, reason: (unspecified), extra: (none), failover: false, available: false, roaming: false, metered: false]}

> info = {[type: MOBILE[LTE] - MOBILE, state: CONNECTED/CONNECTED, reason: connected, extra: ims, failover: false, available: true, roaming: false, metered: false]}


Also I used `var i = connectivityManager.ActiveNetworkInfo.IsConnected;`

and the result is as below:

> Wifi Off+		Cellular On+			Aeroplane on 		=Runtime Error
> Wifi Off+		Cellular off+		Aeroplane off		=Runtime Error
> Wifi off	+	Cellular On+			Aeroplane off		=Connected
> Wifi on	+		Cellular off+		Aeroplane off		=Connected
> Wifi on	+		Cellular on+			Aeroplane off		=Connected

In addition:

`CrossConnectivity.Current.ConnectivityChanged` doesnt listen to any changes in cellular connectivity but works fine if i toggle wifi.

I hope its gonna make your life easier to find out the actual problem. Awaiting eagerly for an update/fix as I am due to publish my app in production environment.

Thanks

**Comment by jamesmontemagno** [comment]
You would want connectivity type changed event. 

What do you mean by runtime error?

Also, if literally it is telling me it is available, is connected... then it is connected...

**Comment by saaabbir** [comment]
i am sorry if am annoying you. basically yeah i want connectivity change event which is not triggering if i toggle cellular data. dont worry about runtime error i fixed that.

**Comment by jamesmontemagno** [comment]
if you toggle it, but still connected then it will not trigger an event as you are still connected.

**Comment by saaabbir** [comment]
lets say my wifi is disconnected and i am on the street. now for some reason my cellular data goes off. its not gonna fire the change event

**Comment by saaabbir** [comment]
when wifi is off and i disconnect cellular from connected state or vice versa it should fire the change event which it doesnt. 

and if i use `connectivityManager.ActiveNetworkInfo.IsConnected` i get the right response instead of `args.IsConnected` or `CrossConnectivity.Current.IsConnected`. 


This is my current stable code snippet where the only problem is it doesnt fire on cellular connectivity change scenario:

```
ConnectivityManager connectivityManager = (ConnectivityManager)Context.GetSystemService(Context.ConnectivityService);
            

            try{
                var i = connectivityManager.ActiveNetworkInfo.IsConnected;
                if (i==true)
                {
                    GlobalConnectivityIndicator.MyConn.ShowConnectivityIndicator = false;
                }
                else
                {
                    GlobalConnectivityIndicator.MyConn.ShowConnectivityIndicator = true;
                }
            }
            catch (Exception ex)
            {
                GlobalConnectivityIndicator.MyConn.ShowConnectivityIndicator = true;
            }


            CrossConnectivity.Current.ConnectivityChanged += (sender, args) =>
            {
                try
                {
                    var i = connectivityManager.ActiveNetworkInfo.IsConnected;
                    if (i == true)
                    {
                        GlobalConnectivityIndicator.MyConn.ShowConnectivityIndicator = false;
                    }
                    else
                    {
                        GlobalConnectivityIndicator.MyConn.ShowConnectivityIndicator = true;
                    }
                }
                catch (Exception ex)
                {
                    GlobalConnectivityIndicator.MyConn.ShowConnectivityIndicator = true;
                }
       };
```

Hope i am making sense.

**Comment by Szymaniuk** [comment]
Meizu M2 Mini - your plugin also returns me **false** for **CrossConnectivity.Current.IsConnected** at Mobile network connection (i.e. LTE).
also **CrossConnectivity.Current.ConnectivityChanged** is not fired on enabling/disabling this Mobile network connection.
Everything works fine on WiFi - **CrossConnectivity.Current.IsConnected** returns **true** and **CrossConnectivity.Current.ConnectivityChanged** is being fired on switching on/off WiFi.

**Comment by jamesmontemagno** [comment]
@Szymaniuk 

You should run this code to validate why your LTE is not returning true:

```
foreach (var network in manager.GetAllNetworks())
                    {
                        try
                        {
                            var info = manager.GetNetworkInfo(network);

                            if (info == null || !info.IsAvailable)
                                continue;

                            if (info.IsConnected)
                                return true;
                        }
                        catch
                        {
                            //there is a possibility, but don't worry
                        }
                    }
return false;
```

**Comment by Szymaniuk** [comment]
Well, I've just updated my mobile device Flyme OS, and now it's returning *IsConnected* correctly at LTE, however it's still not firing *ConnectivityChanged* on switching ON/OFF mobile network (works fine on WiFi ON/OFF).

**Comment by jamesmontemagno** [comment]
When you turn off your mobile network does it swap to wifi?

**Comment by jamesmontemagno** [comment]
You probably want connectivity type changed if that is the case

**Comment by Szymaniuk** [comment]
Well... *ConnectivityChanged* is not getting invoked at all, on mobile network switching on/off, event with having enabled/connected WiFi, or disabled/disconnected WiFi.
It's just not invoked at all. With WiFi enabling/disabling, it's working fine (no matter if mobile network is enabled on disabled).

Chinese devices... 🥇

**Comment by jamesmontemagno** [comment]
Pull down the code and test out the projects and see why, without your device I can't debug it.

**Comment by saaabbir** [comment]
Hi again James, what devices are you trying it on? Lets see if i can manage one and then i will be able to see if its behaving the same. Alternatively if you can get hold of a Samsung S8/S8+ you can test it too im sure if you dont mind. Just keep your wifi turned off and then try to toggle your cellular connection to see if its firing the change event. Im sorry to disturb you again and again.
Also i will try to pull your entire project and see if i can find the issue. But i am afraid i am too busy right now to spend time on it.
I will definitely give you a heads up if i can find anything.

Thanks

**Comment by jamesmontemagno** [comment]
I test on nexus 6, alcatel device, and a blu device.

**Comment by Szymaniuk** [comment]
Well, I've found "workaround" for that - on switching On/Off mobile network **ConnectivityTypeChanged** event is being invoked, and it's fine just to check whether there is network connection availble there, and against **ConnectivityChanged** as well 👍 .

**Comment by saaabbir** [comment]
Hey Szymaniuk,
That is a great news. I will give it a shot tomorrow and let you know.
Thanks a lot

**Comment by saaabbir** [comment]
Hi again James and Szymaniuk,

I used connectivity type changed handler and it worked perfectly. Thanks for your solution Szymaniuk.

**Comment by Szymaniuk** [comment]
For me it's also working properly, even on crappy chinese devices 👍 .
