### ISSUE TITLE
Android: Make ACCESS_WIFI_STATE permission optional

### ISSUE THREAD

**Issue by branohricardo** [jamesmontemagno/ConnectivityPlugin#92]
## Request Information

The ACCESS_WIFI_STATE seems to be used only in the Bandwidths property which I think is not used by most of the applications that want to just check whether the device has an internet connection or not. Therefore the application asks for a permission that is actually not needed in the application.

## Proposal
It would be nice to have this permission optional - e.g. just specify in the documentation that if a developer wants to use the Bandwidths property on Android, an ACCESS_WIFI_STATE permission must be added manually and then just remove it from the `AssemblyInfo.cs`.

**Comment by jamesmontemagno** [comment]
It does not have to ask for a permission at all besides at install, and if you are targeting newer sdks then it wont show up. All my plugins add in require permissions by design.

**Comment by branohricardo** [comment]
That is actually the problem. If a developer adds the ConnectivityPlugin at a later stage after the application has already been uploaded to the store and is available for download, some users might be stuck with the old version as it requires a manual confirmation of the new permission(ACCESS_WIFI_STATE) to update the app - even though the app doesn't need it.
