### ISSUE TITLE
Can't open pdb file ...\packages\Xam.Plugin.Connectivity.3.0.2\lib\netstandard1.0\Plugin.Connectivity.pdb

### ISSUE THREAD

**Issue by aphex3k** [jamesmontemagno/ConnectivityPlugin#93]
I'm experiencing the same issue with the connectivity plugin that I already filed over at the SQLite.Net pcl repo. 
https://github.com/praeclarum/sqlite-net/issues/614

Frank basically  resolved the issue by disable portable debug symbols because he was building with mono.

## Bug Information

Version Number of Plugin: 3.0.2
Version of VS: 2015 Professional
Versions of other things you are using: MSBuild 14.0

### Steps to reproduce the Behavior

Create a Windows 8.1 or Windows Phone 8 project using the connectivity plugin and try to compile the project from the command line using MSBuild

    "C:\Program Files (x86)\MSBuild\14.0\bin\amd64\MSBuild.exe" /m /target:<redacted>_Windows8_1 /p:Configuration=Release /p:Platform="Any CPU" <redacted>.mobile.sln

The step `_GenerateAppxSymbolPackage` fails and subsequently it fails to generate the App store container

    ....
    _GenerateAppxSymbolPackage:
         C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\PDBCopy.exe <redacted>.Windows8.1\bin\Release\<redacted>.Windows8.1.pdb obj\Release\Str
         ipped\<redacted>.Windows8.1.pdb -p
         C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\PDBCopy.exe <redacted>\packages\CommonServiceLocator.1.3\lib\portable-net4+sl5+netcore45+wpa81
         +wp8\Microsoft.Practices.ServiceLocation.pdb obj\Release\Stripped\Microsoft.Practices.ServiceLocation.pdb -p
         C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\PDBCopy.exe <redacted>\packages\Xam.Plugin.Connectivity.3.0.2\lib\netstandard1.0\Plugin.Connec
         tivity.pdb obj\Release\Stripped\Plugin.Connectivity.pdb -p
         Can't open pdb file <redacted>\packages\Xam.Plugin.Connectivity.3.0.2\lib\netstandard1.0\Plugin.Connectivity.pdb
     2>STRIPPRIVATESYMBOLS : error : EC_FILE_SYSTEM [<redacted>.Windows8.1\<redacted>.Windows8.1.csproj]
         <redacted>.Windows8.1 -> <redacted>.Windows8.1\AppPackages\<redacted>.Windows8.1_1.0.0.0_AnyCPU_Test\<redacted>.Windows8.1_1.0.0.0_AnyCPU.appxsym
       _CreateAppStoreContainer:
         Adding file '<redacted>.Windows8.1_1.0.0.0_AnyCPU.appx'.
         Adding file '<redacted>.Windows8.1_1.0.0.0_AnyCPU.appxsym'.
     2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(2774,5): error APPX0002: Task 'CreateAppStoreContainer' failed. Could not find file '<redacted>.Windows8.1\AppPackages\<redacted>.Windows8.1_1.0.0.0_AnyCPU_Test\<redacted>.Windows8.1_1.0.0.0_AnyCPU.appxsym'.\r [<redacted>.Windows8.1\<redacted>.Windows8.1.csproj]
       C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(2774,5): error APPX0002:  [<redacted>.Windows8.1.csproj]
     2>Done Building Project "<redacted>.Windows8.1\<redacted>.Windows8.1.csproj" (default targets) -- FAILED.
     1>Done Building Project "<redacted>.mobile.sln" (<redacted>_Windows8_1 target(s)) -- FAILED.
    
    Build FAILED.
### Expected Behavior

Well I expected MSBuild to generate the binary I can then take and upload to HockeyApp for example.

### Actual Behavior

Compilation fails...

**Comment by jamesmontemagno** [comment]
I don't support those platforms anymore, so be aware of that. 

seems like I could just change it to "Full" i guess for the .net standard library, currently it is doing the portable for the pdb.

**Comment by aphex3k** [comment]
Understood, fair enough. My current workaround is to have an intermediary step after restoring nuget packages and before MSBuild to remove the .pdb from the packages folder. This will at least compile the project...

**Comment by jamesmontemagno** [comment]
I have asked the .NET Team and they are looking at it, but I use VS 2017 and haven't had any issues with this at all.

I don't plan on changing anything though.

**Comment by aphex3k** [comment]
I resolved the issue by adding an additional step to my CI environment that removed the `.pdb` files after restoring the nuget package. That works for what I need it to do. Thanks James.
