### ISSUE TITLE
Compilation fails on VS 2015 UWP project

### ISSUE THREAD

**Issue by fbua** [jamesmontemagno/ConnectivityPlugin#94]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.2
Device Tested On: Windows 10 Pro Version 1703
Simulator Tested On: 
Version of VS: 2015 Pro
Version of Xamarin: 4.6.0.297
Versions of other things you are using:

### Steps to reproduce the Behavior
Adding the plug-in in a UWP project and building using Release configuration
### Expected Behavior
The compilation builds the app package.
### Actual Behavior
The compilation fails with the following error: OutOfMemoryException
### Code snippet
Launching 'C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\tools\Gatekeeper.exe @"D:\Sviluppo\Mobile\Xamarin\OrdCommPatti\OrdCommPatti\OrdCommPatti.UWP\obj\x86\Release\ilc\intermediate\gkargs.rsp"'
8>  Microsoft (R) .NET Native Gatekeeper Version 1.0.24208.01 
8>  Copyright (C) Microsoft Corporation.  All rights reserved. 
8>   
8>  Checking assembly 'D:\Sviluppo\Mobile\Xamarin\OrdCommPatti\OrdCommPatti\OrdCommPatti.UWP\obj\x86\Release\ilc\in\CheapApp.Common.dll'. 
8>  Checking assembly 'D:\Sviluppo\Mobile\Xamarin\OrdCommPatti\OrdCommPatti\OrdCommPatti.UWP\obj\x86\Release\ilc\in\FBE.Common.Xamarin.dll'. 
8>  Checking assembly 'D:\Sviluppo\Mobile\Xamarin\OrdCommPatti\OrdCommPatti\OrdCommPatti.UWP\obj\x86\Release\ilc\in\Microsoft.WindowsAzure.Messaging.Managed.dll'. 
8>  Checking assembly 'D:\Sviluppo\Mobile\Xamarin\OrdCommPatti\OrdCommPatti\OrdCommPatti.UWP\obj\x86\Release\ilc\in\Newtonsoft.Json.dll'. 
8>  Checking assembly 'D:\Sviluppo\Mobile\Xamarin\OrdCommPatti\OrdCommPatti\OrdCommPatti.UWP\obj\x86\Release\ilc\in\OrdCommPatti.dll'. 
8>  Checking assembly 'D:\Sviluppo\Mobile\Xamarin\OrdCommPatti\OrdCommPatti\OrdCommPatti.UWP\obj\x86\Release\ilc\in\OrdCommPatti.NotificationBackgroundTask.winmd'. 
8>  Checking assembly 'D:\Sviluppo\Mobile\Xamarin\OrdCommPatti\OrdCommPatti\OrdCommPatti.UWP\obj\x86\Release\ilc\in\OrdCommPatti.UWP.exe'. 
8>  Checking assembly 'D:\Sviluppo\Mobile\Xamarin\OrdCommPatti\OrdCommPatti\OrdCommPatti.UWP\obj\x86\Release\ilc\in\Plugin.Connectivity.Abstractions.dll'. 
8>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(318,5): error : Eccezione non gestita: OutOfMemoryException.
8>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(318,5): error : ILT0005: 'C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\tools\Gatekeeper.exe @"D:\Sviluppo\Mobile\Xamarin\OrdCommPatti\OrdCommPatti\OrdCommPatti.UWP\obj\x86\Release\ilc\intermediate\gkargs.rsp"' returned exit code -532462766
### Workaround
Downgrade to version 2.3.0, maybe latest version uses some framework incompatible with VS 2015?

**Comment by Sasha111ua** [comment]
Can confirm this problem on vsts

**Comment by jamesmontemagno** [comment]
What version of VS 2015 are you running and what version of .NET Native?

Additionally what is your NuGet for UWP Microsoft.NETCore.UniversalWindowsPlatform set to?

**Comment by fbua** [comment]
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02046

Net Native version 1.4.24208.01, but the project is compiled against version 1.3

In my project I use Microsoft.NETCore.UniversalWindowsPlatform version 5.2.3

**Comment by jamesmontemagno** [comment]
I have asked the .NET Team and they are looking at it, but I use VS 2017 and haven't had any issues with this at all.

**Comment by Sasha111ua** [comment]
fixed by adding to the UWP project a BehaviorsXamlSDKManaged nuget package instead of using it like an extension.

**Comment by jamesmontemagno** [comment]
So did it have something to do with this plugin or no? A bit confused here.

**Comment by Sasha111ua** [comment]
I had <SDKReference Include="BehaviorsXamlSDKManaged, Version=12.0"> included in my XXX.UWP.csproj and solution was failing to build on VSTS with OutOfMemory exception after I updated version of your plugin to 3.0.2. I removed "behaviours" package from referenced extensions and added it via nuget. After that solution builds fine.

**Comment by fbua** [comment]
In my project I don't use that extension.
I've also tried with a blank solution adding only the plug-in and the exception still occurs.
I've attached the test solution.

[TestCrossConnectivity.zip](https://github.com/jamesmontemagno/ConnectivityPlugin/files/1273076/TestCrossConnectivity.zip)

**Comment by jamesmontemagno** [comment]
This is definitely a build time issues and should be reported on the .net native GitHub wherever that lives and probably not here.

**Comment by jamesmontemagno** [comment]
Will continue to ask the team though.

**Comment by fbua** [comment]
I agree. 
I managed to solve the issue rebuilding your solution using VS 2015.
