### ISSUE TITLE
IsConnected always returns false on Android.

### ISSUE THREAD

**Issue by BenDevelopment** [jamesmontemagno/ConnectivityPlugin#95]
Hi there. I'm using this plugin for my Xamarin.Forms project. My problem is, anytime I check the internet connection, I get `false` on Android (others platforms not tested).

## Bug Information

Version Number of Plugin: 3.0.3-beta123
Device Tested On: Xiaomi Redmi Note 3 (CyanogenMod  12.1 Android 5.1.1)
Simulator Tested On: Android 5.1.1 API 22
Version of VS: Community 2017 (15.2 - 26430.16 Release)
Version of Xamarin: 2.3.5.256-pre6
Versions of other things you are using:

### Steps to reproduce the Behavior
Create a new project, install this package nuget, run the code.

### Expected Behavior
`connectivity.IsConnected;` should return true because the device/emulator is connected to network (I can use navigator and load websites).
### Actual Behavior
`connectivity.IsConnected;` always returns false.

### Code snippet

```
        public static bool DoIHaveInternet()
        {
            if (!CrossConnectivity.IsSupported)
                return true;

            //Do this only if you need to and aren't listening to any other events as they will not fire.
            using (var connectivity = CrossConnectivity.Current)
            {
                return connectivity.IsConnected; // This always returns false
            }
        }
```

### Screenshotst
No needed I guess...

**Comment by jamesmontemagno** [comment]
What about the current stable?

**Comment by jamesmontemagno** [comment]
Works fine for me on all my devices.

You should check:


```
oreach (var network in manager.GetAllNetworks())
                    {
                        try
                        {
                            var info = manager.GetNetworkInfo(network);

                            if (info == null || !info.IsAvailable)
                                continue;

                            if (info.IsConnected)
                                return true;
                        }
                        catch
                        {
                            //there is a possibility, but don't worry
                        }
                    }
return false;
```
 in your Android project and see what is continuing and not returning true.

**Comment by olivierclaude** [comment]
Hello, I've the same issue with the latest version of this plugin.
Tested on Android Emulator Nexus 5X API 26, Android 8.0.

After downgrading to 2.4.0.76-beta it works fine.

**Comment by FK-Alkaersig** [comment]
Installed the plugin as part of Xamarin University courses. It detects WiFi but returns false if only cellular connection is available.

The problem seems to be with the 4.x (beta) version of the plugin. Downgrading to 3.0.2 (stable) solved the issue.

**Comment by jamesmontemagno** [comment]
@olivierclaude did you try the stable version?

@FK-Alkaersig what device?

**Comment by FK-Alkaersig** [comment]
Samsung Galaxy S6 / Samsung Galaxy S7 Edge (live debugged on botch devices with same result).

**Comment by jamesmontemagno** [comment]
@FK-Alkaersig 

can you try to run this code in your android project and see why it is returning false:


```
var manager = (ConnectivityManager)(Application.Context.GetSystemService(Context.ConnectivityService));
foreach (var network in manager.GetAllNetworks())
                    {
                        try
                        {
                           var info = manager.GetNetworkInfo(network);

                            if (info == null || !info.IsAvailable || info.Subtype.HasFlag(ConnectivityType.Dummy))
                                continue;

                            if (info.IsConnected)
                                return true;
                        }
                        catch
                        {
                            //there is a possibility, but don't worry
                        }
                    }
return false;
```

**Comment by jamesmontemagno** [comment]
@FK-Alkaersig can you also show me the code you are trying.. is is just the IsConnected call?

**Comment by jamesmontemagno** [comment]
Also @FK-Alkaersig what version of android are they running

**Comment by FK-Alkaersig** [comment]
Running on Android 7.0. I will test the code in the project later today. 

I don't know if it helps, but when WiFi is on, the list of connection contains "other" and "wifi". So even when WiFi is on, cellular is not in the list. I will provide you the results of the test in a few hours.

**Comment by JanKonopka** [comment]
I have the same problem with real Android 7.1 device and latest stable version of your NuGet plugin, IsConnected always returns false on cellular, works fine on wifi.

**Comment by FK-Alkaersig** [comment]
I did both a:
`CrossConnectivity.Current.IsConnected`
Which returns false without WiFi.

And:
`CrossConnectivity.Current.ConnectionTypes`
Which is empty without WiFi.

**Comment by FK-Alkaersig** [comment]
Hello @jamesmontemagno .

I ran your code now and it seems like the format has changed. This is the result of the INFO:
`{[type: MOBILE[LTE] - MOBILE, state: CONNECTED/CONNECTED, reason: (unspecified), extra: internet, failover: false, available: true, roaming: false, metered: true]}`

So the type is no longer just "MOBILE" but "MOBILE" suffixed by the networktype. And as far as i could tell from the code it just checks for "Type == Mobile". So what is the difference from v3 to v4? Did you upgrade some underlying Android components ?

**Comment by jamesmontemagno** [comment]
So, that is for maybe why it isn't returning "Mobile" on the network type, but on the `info` there is a property:
```
  if (info.IsConnected)
    return true;
```

In v4 (in beta) I added a check for Dummy networks: info.Subtype.HasFlag(ConnectivityType.Dummy)

can you see WHY it is not getting to IsConnected for that info?

**Comment by FK-Alkaersig** [comment]
I'll try to debug it and look into it tomorrow when i'm back at work!

**Comment by Szymaniuk** [comment]
+1 same at 7.1.2 - **CrossConnectivity.Current.IsConnected** returns **false** for mobile (cellular) network, event when connection IS available.

However my implementation already "workarounds" such behaviour, because indeed I'm checking **CrossConnectivity.Current.IsConnected** firstly, but if it's **false**, then I'm trying to invoke **CrossConnectivity.Current.IsRemoteReachable()**, which is returning **true** (even in such case - for mobile network, when given address is pingable).

**Comment by FK-Alkaersig** [comment]
Hello @jamesmontemagno 

I looked into it now. The problem is indeed your check for Dummy networks. This is the content of the Subtype collection:
`Android.Net.ConnectivityType.Dummy | Android.Net.ConnectivityType.MobileDun | Android.Net.ConnectivityType.Wifi`

The value of info.IsConnected is indeed **true**, but is never reached due to the loop continueing because of the collection holding the dummy along with the valid Mobile and WiFi networks.

**Comment by jamesmontemagno** [comment]
got it
yeah i thought maybe it would cause some issues. That is sad :(

It may bring back: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/90, which actually probably wasn't an issue. let me remove that code.

**Comment by FK-Alkaersig** [comment]
Good to hear. I'll be happy to test #90 on my devices. We are going to use those events anyway in our implementation.
