### ISSUE TITLE
CrossConnectivity.Current.IsConnected always return false when WiFi is off

### ISSUE THREAD

**Issue by asafgo** [jamesmontemagno/ConnectivityPlugin#96]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:  4.0.0-beta130
Device Tested On: Xiaomi Mi5s Plus, Sony Z3 (D5803)
Simulator Tested On:
Version of VS:  15.3.3
Version of Xamarin:  4.6.0.299
Versions of other things you are using:

### Steps to reproduce the Behavior
When switching WiFi off and stay with Cellular data, IsConnected is always false. no problem when using WiFi.

### Expected Behavior
When switching WiFi off and stay with Cellular data, IsConnected  should be true as I can use Facebook for example.
### Actual Behavior
Always return false.

### Code snippet

```
public Command MyCommand
        {
            get
            {
                return new Command(async () =>
                {
                    var connectivity = CrossConnectivity.Current;
                    var boolConnected = connectivity.IsConnected;
                    var reachable = await connectivity.IsRemoteReachable("motzcod.es");
                });
            }
        }
```

**Comment by jamesmontemagno** [comment]
Did you try the current stable?

**Comment by ScriptSun** [comment]
Hi @jamesmontemagno 

It's same here for me on wifi it returns always false 

Regards

**Comment by asafgo** [comment]
Yes I tried stable and still the same.

**Comment by jamesmontemagno** [comment]
Run this code in your android app:

```
var manager = (ConnectivityManager)(Application.Context.GetSystemService(Context.ConnectivityService));
foreach (var network in manager.GetAllNetworks())
                    {
                        try
                        {
                           var info = manager.GetNetworkInfo(network);

                            if (info == null || !info.IsAvailable)
                                continue;

                            if (info.IsConnected)
                                return true;
                        }
                        catch
                        {
                            //there is a possibility, but don't worry
                        }
                    }
return false;
```

This will tell you exactly why it is returning false and not true. Let me know what seems to be causing the issue on it.

**Comment by asafgo** [comment]
I am using Xamarin Forms not Android native project so I have no clue how and where should I run your code.

**Comment by jamesmontemagno** [comment]
Put it in your Android project

**Comment by asafgo** [comment]
info = {[type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "xxxxxx", roaming: false, failover: false, isAvailable: true]}

info = {[type: MOBILE[HSPA], state: CONNECTED/CONNECTED, reason: connected, extra: xxxxxx, roaming: false, failover: false, isAvailable: true]}

**Comment by jamesmontemagno** [comment]
Looks like it will return true then... so doesn't seem to be an issue I do assume?

**Comment by asafgo** [comment]
It does not work when using the plugin in Xamarin Forms but I will implement it using DependencyService with the help of your code.
thanks!

**Comment by jamesmontemagno** [comment]
This is the code that literally the plugin calls. 

So it must work.

You can also open the "test" project in this repo and try for yourself.

**Comment by jamesmontemagno** [comment]
As you can literally see right here: https://github.com/jamesmontemagno/ConnectivityPlugin/blob/master/src/Connectivity.Plugin.Android/ConnectivityImplementation.cs#L65

**Comment by deepakyogi1995** [comment]
Hello @asafgo 

I resolved this issue :)

this issue was occurs because linking is set sdk and user assemblies then i replaced sdk and user assemblies to sdk assemblies.

this step work for me in release mode and debug mode.
