### ISSUE TITLE
CrossConnectivity.Current.IsReachable() returns false for Android, true for iOS when connected

### ISSUE THREAD

**Issue by philtomblin** [jamesmontemagno/ConnectivityPlugin#97]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.2
Device Tested On: N/A
Simulator Tested On: Android 6.0 (API 23), iPhone 7 iOS 10.3
Version of VS: VS for Mac Professional 7.1 (build 1297)
Version of Xamarin: Xamarin.Forms 2.3.4.270, Xamarin.Android 23.3.0, Xamarin.iOS 1.0
Versions of other things you are using: NETStandard.Library 1.6.1

### Steps to reproduce the Behaviour
Run Xamarin.Forms app in emulators while host laptop is connected to the internet

### Expected Behaviour
`CrossConnectivity.Current.IsReachable("hostname")` returns `true`

### Actual Behaviour
`CrossConnectivity.Current.IsReachable("{hostname}")` returns `true` for iOS
`CrossConnectivity.Current.IsReachable("{hostname}")` returns `false` for Android

### Code snippet
```
var connected = await Plugin.Connectivity.CrossConnectivity.Current.IsReachable("{hostname}.azurewebsites.net");
if (connected == false)
	return;
```

Commenting out this block before running in Android emulator results in the the app continuing to access the Azure app service okay, confirming connectivity is present.

### Screenshots
N/A

**Comment by jamesmontemagno** [comment]
This logic has been completely re-written for 4.0 so you should test that out:
https://montemagno.com/connectivity-plugin-4-0-important-and-awesome-changes/

Also... if you are checking a remote service you would want "IsRemoteReachable"

**Comment by philtomblin** [comment]
Thanks James - that works great. Keep up the awesome work!

**Comment by danysalas** [comment]
Hi James, 

I installed version 4.0 and I´m trying to use the "IsReachable" method to test if a local server is reachable. The device is connected to a wifi router with no internet connection (local connectivity only). I tried to send data through HttpClient and it is working fine. However, CrossConnectivity always returns false.
Can you please point me in the right direction? I´ll truly appreciate your help. 

Code Snippet: 
---------------
```
public async Task<Response> CheckConnection()
        {
                var WebAddress = "10.0.0.100";

                var isLocalReachable = await CrossConnectivity.Current.IsReachable(WebAddress);
                if (!isLocalReachable)
                {
                    return new Response
                    {
                        IsSuccess = false,
                        Message = "Check Connection.",
                    };
                }
                  return new Response
                  {
                      IsSuccess = true,
                      Message = "Ok",
                  };
            }
```
