### ISSUE TITLE
ConnectivityChanged Event firing for older Samsung S4, but not newer Samsung S8

### ISSUE THREAD

**Issue by CurtisHerrick** [jamesmontemagno/ConnectivityPlugin#98]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On: Samsung S4 and Samsung S8
Simulator Tested On: None
Version of VS: Visual Studio Professional 2015
Version of Xamarin:  Xamarin 4.3.0.795 / Xamarin.Android 7.1.0.43
Versions of other things you are using:

### Steps to reproduce the Behavior
I load my app and depending on the device, the broadcasts don't seem to work.
On the older S4, the ConnectivityChanged event is firing and my app reacts as I've coded it to.
On the newer S8, the ConnectivityChanged event is not firing, so my app has to proactively discover the loss of connectivity (when the use tries to access network resources) instead of reactively deal with it for the user.

I have read various sources about registering for events working differently past Droid OS ver 24:
[https://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html#MonitorChanges](Android Docs on Internet Connectivity)
Excerpt:

> Apps targeting Android 7.0 (API level 24) and higher do not receive CONNECTIVITY_ACTION broadcasts if they declare the broadcast receiver in their manifest. Apps will still receive CONNECTIVITY_ACTION broadcasts if they register their BroadcastReceiver with Context.registerReceiver() and that context is still valid.

Is this the problem for my S8?  Is somehow the context not valid?

### Expected Behavior
I expected the S8 to work like the S4, but I do realize that there is a considerable OS version difference there.

### Actual Behavior
ConnectivityChanged Event not firing for the (much newer) S8.

### Code snippet
Not much to see for code, as I use the plugin.

### Screenshots
N/A.

**Comment by jamesmontemagno** [comment]
Did you try the "ConnectivityTypeChanged" instead, most likely it gets the new connection as I wait 1 second on just ConnectivityChanged.

The TypeChanged will trigger no matter what.

Yes, I know about the changes in API 24, however it does registers via RegisterReceiver when you spin it up. So it works as desired.

**Comment by CurtisHerrick** [comment]
Excellent.  I will surely try that asap!

Thanks again,
- Curtis Herrick
via phone gmail

**Comment by CurtisHerrick** [comment]
## Success
I added also subscribing to the ConnectivityTypeChanged event and that did the trick.  It does seem to fire in more scenarios than the ConnectivityChanged event.
## Tweak
One tweak I had to make was to move my triggered connectivity check code to an async method and put a delay in there for 1 second before checking for connectivity.  When you're down to no data connectivity, and you connect to WIFI, the ConnectivityTypeChanged event can fire when in a Connecting state and not yet a Connected state.  If my app didn't wait, it seemed like the event wasn't fired because the app still behaved as if it was disconnected.  In reality, my app jumped the gun - it has to hold off for a second before actually checking for a Connected state.  Add the 1 second wait and it's working _very_ slick.

Thanks!  - Curtis
