### ISSUE TITLE
Possible fix/improvement for Android for more accurate detection of Mobile Data?

### ISSUE THREAD

**Issue by CurtisHerrick** [jamesmontemagno/ConnectivityPlugin#99]
I've noticed while testing my Samsung S8 (using Verizon Wireless), that I see that the connectivity plug in does not accurately recognize a loss of mobile data when Mobile Data is disabled in the device settings (pull down from the top).

## Bug Information
Version Number of Plugin:
Device Tested On: Samsung S4 and Samsung S8
Simulator Tested On: None
Version of VS: Visual Studio Professional 2015
Version of Xamarin:  Xamarin 4.3.0.795 / Xamarin.Android 7.1.0.43
Versions of other things you are using:
N/A

Debugging the plugin code, it sees VZWINS and VZAPPS networks (both being in a connected state) while Mobile Data has been disabled, but still returns true (Connected), which is a false-positive for my app (which uses a browser control to present web content).

However, if I use the following code:

`            //get the active network's status
            ConnectivityManager oManager = (ConnectivityManager)Application.Context.GetSystemService(Context.ConnectivityService);
            NetworkInfo oActiveNetwork = oManager.ActiveNetworkInfo;
            bool bIsConnected = oActiveNetwork?.IsConnectedOrConnecting ?? false;
            return (bIsConnected ? eConnectivityState.Connected : eConnectivityState.Disconnnected);`

it seems to accurately detect the presence of an enabled data network.

With WIFI ON / Mobile Data ON : oAN.Type is Wifi and isConnected is true.
With WIFI ON / Mobile Data OFF : oAN.Type is Wifi and isConnected is true.
With WIFI OFF / Mobile Data ON : oAN.Type is Mobile and isConnected is true.
With WIFI OFF / Mobile Data OFF : oAN is null and therefore isConnected is false.
With Airplane mode ON : oAN is null and therefore isConnected is false.

Where VZWIMS and VZWAPP networks show up as connected (which fools the adapter), the ActiveNetworkInfo call returns null when there is no WIFI, or Mobile Data is disabled, or Airplane mode is on, which is an accurate read on the device situation.  I do not see any version info on this method saying what versions of Android it is valid for.  Seems to be valid for all droid OS's.

**Comment by jamesmontemagno** [comment]
This is the incorrect way of doing it:

https://github.com/jamesmontemagno/ConnectivityPlugin/issues/43
